name: Pull request check

on: [pull_request]

jobs:
  block-fixup-merge:
    runs-on: ubuntu-latest
    name: Block fixup commits

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Block fixup commit merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
