/* This file was generated by Supernova, don't change manually */
export const actionButtonPlainActive = '#d8ccf7';
export const actionButtonPlainBorder = '#fff0';
export const actionButtonPlainContent = '#6145ad';
export const actionButtonPlainDefault = '#fff0';
export const actionButtonPlainHover = '#f2effd';

export const actionButtonPrimaryActive = '#3a2967';
export const actionButtonPrimaryBorder = '#fff0';
export const actionButtonPrimaryContent = '#fff';
export const actionButtonPrimaryDefault = '#6145ad';
export const actionButtonPrimaryHover = '#4d378a';

export const actionButtonSecondaryActive = '#d8ccf7';
export const actionButtonSecondaryBorder = '#d8ccf7';
export const actionButtonSecondaryContent = '#6145ad';
export const actionButtonSecondaryDefault = '#f2effd';
export const actionButtonSecondaryHover = '#ece7fb';

export const actionButtonTertiaryActive = '#e2e2e2';
export const actionButtonTertiaryBorder = '#e2e2e2';
export const actionButtonTertiaryContent = '#515151';
export const actionButtonTertiaryDefault = '#f6f6f6';
export const actionButtonTertiaryHover = '#ededed';

export const actionLinkPrimaryActive = '#3a2967';
export const actionLinkPrimaryDefault = '#6145ad';
export const actionLinkPrimaryHover = '#4d378a';

export const actionLinkSecondaryActive = '#a713b4';
export const actionLinkSecondaryDefault = '#515151';
export const actionLinkSecondaryHover = '#464646';

export const actionLinkTertiaryActive = '#515151';
export const actionLinkTertiaryDefault = '#6a6a6a';
export const actionLinkTertiaryHover = '#5f5f5f';

export const actionLinkVisitedDefault = '#2f8172';

export const backgroundBackdrop = '#0b1c2199';

export const backgroundInteractiveActive = '#ededed';
export const backgroundInteractiveDefault = '#fff0';
export const backgroundInteractiveHover = '#f6f6f6';

export const backgroundPrimary = '#fff';
export const backgroundSecondary = '#f6f6f6';
export const backgroundTertiary = '#fff9eb';

export const borderBasic = '#e9e9e9';
export const borderFocus = '#4666ae';

export const borderInteractiveActive = '#a0a0a0';
export const borderInteractiveDefault = '#b9b9b9';
export const borderInteractiveHover = '#aeaeae';
export const borderInteractiveSelected = '#6145ad';

export const custom01Active = '#fff';
export const custom01BackgroundBasic = '#2e41dd';
export const custom01BackgroundSubtle = '#eaecfc';
export const custom01BorderBasic = '#2e41dd';
export const custom01BorderSubtle = '#2c43ff';
export const custom01ContentBasic = '#2e41dd';
export const custom01ContentSubtle = '#fff';
export const custom01Default = '#fff';
export const custom01Hover = '#fff';

export const custom02Active = '#fff';
export const custom02BackgroundBasic = '#ff600e';
export const custom02BackgroundSubtle = '#fff0e7';
export const custom02BorderBasic = '#ff600e';
export const custom02BorderSubtle = '#fff0e7';
export const custom02ContentBasic = '#ff600e';
export const custom02ContentSubtle = '#fff';
export const custom02Default = '#fff';
export const custom02Hover = '#fff';

export const custom03Active = '#fff';
export const custom03BackgroundBasic = '#ff0e9f';
export const custom03BackgroundSubtle = '#ffe6f5';
export const custom03BorderBasic = '#ff0e9f';
export const custom03BorderSubtle = '#ffe7f6';
export const custom03ContentBasic = '#ca2026';
export const custom03ContentSubtle = '#fff';
export const custom03Default = '#fff';
export const custom03Hover = '#fff';

export const custom04Active = '#fff';
export const custom04BackgroundBasic = '#0effa8';
export const custom04BackgroundSubtle = '#e7fff7';
export const custom04BorderBasic = '#0effa8';
export const custom04BorderSubtle = '#d4ebe3';
export const custom04ContentBasic = '#353131';
export const custom04ContentSubtle = '#353131';
export const custom04Default = '#fff';
export const custom04Hover = '#fff';

export const custom05Active = '#fff';
export const custom05BackgroundBasic = '#a30eff';
export const custom05BackgroundSubtle = '#f6e7ff';
export const custom05BorderBasic = '#a30eff';
export const custom05BorderSubtle = '#d9a7f8';
export const custom05ContentBasic = '#a30eff';
export const custom05ContentSubtle = '#fff';
export const custom05Default = '#fff';
export const custom05Hover = '#fff';

export const disabledBackground = '#f6f6f6';
export const disabledBorder = '#e2e2e2';
export const disabledContent = '#aeaeae';
export const disabledForeground = '#c7c7c7';

export const emotionDangerActive = '#a62929';
export const emotionDangerBackgroundBasic = '#a62929';
export const emotionDangerBackgroundSubtle = '#faebeb';
export const emotionDangerBorderBasic = '#f0c0c0';
export const emotionDangerBorderSubtle = '#f0c0c0';
export const emotionDangerContentBasic = '#7c1f1f';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerDefault = '#cf3333';
export const emotionDangerHover = '#ba2e2e';

export const emotionInformativeActive = '#295ba6';
export const emotionInformativeBackgroundBasic = '#295ba6';
export const emotionInformativeBackgroundSubtle = '#ebf1fa';
export const emotionInformativeBorderBasic = '#c0d3f0';
export const emotionInformativeBorderSubtle = '#c0d3f0';
export const emotionInformativeContentBasic = '#1f447c';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeDefault = '#3372cf';
export const emotionInformativeHover = '#2e67ba';

export const emotionSuccessActive = '#328a7a';
export const emotionSuccessBackgroundBasic = '#328a7a';
export const emotionSuccessBackgroundSubtle = '#ecf7f5';
export const emotionSuccessBorderBasic = '#c3e5df';
export const emotionSuccessBorderSubtle = '#c3e5df';
export const emotionSuccessContentBasic = '#25675b';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessDefault = '#3eac98';
export const emotionSuccessHover = '#389b89';

export const emotionWarningActive = '#ca6533';
export const emotionWarningBackgroundBasic = '#ca6533';
export const emotionWarningBackgroundSubtle = '#fff2ec';
export const emotionWarningBorderBasic = '#fed7c4';
export const emotionWarningBorderSubtle = '#fed7c4';
export const emotionWarningContentBasic = '#984c26';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningDefault = '#fd7e40';
export const emotionWarningHover = '#e4713a';

export const focusFocusRingColor01 = '#d2c2ffb2';

export const formFieldActive = '#fff';
export const formFieldBorderActive = '#a0a0a0';
export const formFieldBorderDefault = '#b9b9b9';
export const formFieldBorderHover = '#aeaeae';
export const formFieldBorderSelected = '#6145ad';
export const formFieldContent = '#1d1d1d';
export const formFieldDanger = '#cf3333';
export const formFieldDefault = '#fff';
export const formFieldHelperText = '#6a6a6a';
export const formFieldHover = '#fafafa';
export const formFieldLabel = '#1d1d1d';
export const formFieldPlaceholder = '#6a6a6a';
export const formFieldSuccess = '#2f8172';
export const formFieldWarning = '#ca6533';

export const gradientBasicOverlayColor01 = '#fff';
export const gradientBasicOverlayColor02 = '#fff0';

export const headerBackground = '#fff';
export const headerItemActive = '#292929';
export const headerItemBackgroundDefault = '#fff0';
export const headerItemBackgroundHover = '#f6f6f6';
export const headerItemBackgroundSelected = '#f2effd';
export const headerItemDefault = '#6a6a6a';
export const headerItemHover = '#333232';
export const headerItemSelected = '#6145ad';
export const headerStripeSelected = '#ffcb3b';
export const headerStripeUnselected = '#ededed';

export const neutralActive = '#1d1d1d';
export const neutralBackgroundBasic = '#1d1d1d';
export const neutralBackgroundSubtle = '#f6f6f6';
export const neutralBorderBasic = '#e2e2e2';
export const neutralBorderSubtle = '#fff';
export const neutralContentBasic = '#132930';
export const neutralContentSubtle = '#fff';
export const neutralDefault = '#363636';
export const neutralHover = '#282828';

export const selectedActive = '#3a2967';
export const selectedContentBasic = '#5314da';
export const selectedContentSubtle = '#fff';
export const selectedDefault = '#6145ad';
export const selectedHover = '#4d378a';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#1d1d1d';
export const textSecondary = '#515151';
export const textTertiary = '#6a6a6a';

export const toggleSelectedBorder = '#2f8172';
export const toggleSelectedContent = '#fff';
export const toggleSelectedDefault = '#3eac98';
export const toggleSelectedHover = '#389b89';
export const toggleUnselectedBorder = '#b9b9b9';
export const toggleUnselectedContent = '#fff';
export const toggleUnselectedDefault = '#1d1d1d';
export const toggleUnselectedHover = '#464646';

export const actionColors = {
  button: {
    plain: {
      active: actionButtonPlainActive,
      border: actionButtonPlainBorder,
      content: actionButtonPlainContent,
      default: actionButtonPlainDefault,
      hover: actionButtonPlainHover,
    },
    primary: {
      active: actionButtonPrimaryActive,
      border: actionButtonPrimaryBorder,
      content: actionButtonPrimaryContent,
      default: actionButtonPrimaryDefault,
      hover: actionButtonPrimaryHover,
    },
    secondary: {
      active: actionButtonSecondaryActive,
      border: actionButtonSecondaryBorder,
      content: actionButtonSecondaryContent,
      default: actionButtonSecondaryDefault,
      hover: actionButtonSecondaryHover,
    },
    tertiary: {
      active: actionButtonTertiaryActive,
      border: actionButtonTertiaryBorder,
      content: actionButtonTertiaryContent,
      default: actionButtonTertiaryDefault,
      hover: actionButtonTertiaryHover,
    },
  },
  link: {
    primary: {
      active: actionLinkPrimaryActive,
      default: actionLinkPrimaryDefault,
      hover: actionLinkPrimaryHover,
    },
    secondary: {
      active: actionLinkSecondaryActive,
      default: actionLinkSecondaryDefault,
      hover: actionLinkSecondaryHover,
    },
    tertiary: {
      active: actionLinkTertiaryActive,
      default: actionLinkTertiaryDefault,
      hover: actionLinkTertiaryHover,
    },
    visited: {
      default: actionLinkVisitedDefault,
    },
  },
};

export const backgroundColors = {
  backdrop: backgroundBackdrop,
  interactive: {
    active: backgroundInteractiveActive,
    default: backgroundInteractiveDefault,
    hover: backgroundInteractiveHover,
  },
  primary: backgroundPrimary,
  secondary: backgroundSecondary,
  tertiary: backgroundTertiary,
};

export const borderColors = {
  basic: borderBasic,
  focus: borderFocus,
  interactive: {
    active: borderInteractiveActive,
    default: borderInteractiveDefault,
    hover: borderInteractiveHover,
    selected: borderInteractiveSelected,
  },
};

export const customColors = {
  _01: {
    hover: custom01Hover,
  },
  _02: {
    hover: custom02Hover,
  },
  _03: {
    hover: custom03Hover,
  },
  _04: {
    hover: custom04Hover,
  },
  _05: {
    hover: custom05Hover,
  },
};

export const disabledColors = {
  background: disabledBackground,
  border: disabledBorder,
  content: disabledContent,
  foreground: disabledForeground,
};

export const emotionColors = {
  danger: {
    active: emotionDangerActive,
    backgroundBasic: emotionDangerBackgroundBasic,
    backgroundSubtle: emotionDangerBackgroundSubtle,
    borderBasic: emotionDangerBorderBasic,
    borderSubtle: emotionDangerBorderSubtle,
    contentBasic: emotionDangerContentBasic,
    contentSubtle: emotionDangerContentSubtle,
    default: emotionDangerDefault,
    hover: emotionDangerHover,
  },
  informative: {
    active: emotionInformativeActive,
    backgroundBasic: emotionInformativeBackgroundBasic,
    backgroundSubtle: emotionInformativeBackgroundSubtle,
    borderBasic: emotionInformativeBorderBasic,
    borderSubtle: emotionInformativeBorderSubtle,
    contentBasic: emotionInformativeContentBasic,
    contentSubtle: emotionInformativeContentSubtle,
    default: emotionInformativeDefault,
    hover: emotionInformativeHover,
  },
  success: {
    active: emotionSuccessActive,
    backgroundBasic: emotionSuccessBackgroundBasic,
    backgroundSubtle: emotionSuccessBackgroundSubtle,
    borderBasic: emotionSuccessBorderBasic,
    borderSubtle: emotionSuccessBorderSubtle,
    contentBasic: emotionSuccessContentBasic,
    contentSubtle: emotionSuccessContentSubtle,
    default: emotionSuccessDefault,
    hover: emotionSuccessHover,
  },
  warning: {
    active: emotionWarningActive,
    backgroundBasic: emotionWarningBackgroundBasic,
    backgroundSubtle: emotionWarningBackgroundSubtle,
    borderBasic: emotionWarningBorderBasic,
    borderSubtle: emotionWarningBorderSubtle,
    contentBasic: emotionWarningContentBasic,
    contentSubtle: emotionWarningContentSubtle,
    default: emotionWarningDefault,
    hover: emotionWarningHover,
  },
};

export const focusColors = {
  focusRing: {
    color01: focusFocusRingColor01,
  },
};

export const formFieldColors = {
  active: formFieldActive,
  borderActive: formFieldBorderActive,
  borderDefault: formFieldBorderDefault,
  borderHover: formFieldBorderHover,
  borderSelected: formFieldBorderSelected,
  content: formFieldContent,
  danger: formFieldDanger,
  default: formFieldDefault,
  helperText: formFieldHelperText,
  hover: formFieldHover,
  label: formFieldLabel,
  placeholder: formFieldPlaceholder,
  success: formFieldSuccess,
  warning: formFieldWarning,
};

export const gradientColors = {
  basicOverlay: {
    color02: gradientBasicOverlayColor02,
  },
};

export const headerColors = {
  background: headerBackground,
  itemActive: headerItemActive,
  itemBackgroundDefault: headerItemBackgroundDefault,
  itemBackgroundHover: headerItemBackgroundHover,
  itemBackgroundSelected: headerItemBackgroundSelected,
  itemDefault: headerItemDefault,
  itemHover: headerItemHover,
  itemSelected: headerItemSelected,
  stripeSelected: headerStripeSelected,
  stripeUnselected: headerStripeUnselected,
};

export const neutralColors = {
  active: neutralActive,
  backgroundBasic: neutralBackgroundBasic,
  backgroundSubtle: neutralBackgroundSubtle,
  borderBasic: neutralBorderBasic,
  borderSubtle: neutralBorderSubtle,
  contentBasic: neutralContentBasic,
  contentSubtle: neutralContentSubtle,
  default: neutralDefault,
  hover: neutralHover,
};

export const selectedColors = {
  active: selectedActive,
  contentBasic: selectedContentBasic,
  contentSubtle: selectedContentSubtle,
  default: selectedDefault,
  hover: selectedHover,
};

export const shadowColors = {
  shadow100: {
    color01: shadowShadow100Color01,
  },
  shadow200: {
    color01: shadowShadow200Color01,
  },
  shadow300: {
    color01: shadowShadow300Color01,
  },
  shadow400: {
    color01: shadowShadow400Color01,
  },
};

export const textColors = {
  primary: textPrimary,
  secondary: textSecondary,
  tertiary: textTertiary,
};

export const toggleColors = {
  selectedBorder: toggleSelectedBorder,
  selectedContent: toggleSelectedContent,
  selectedDefault: toggleSelectedDefault,
  selectedHover: toggleSelectedHover,
  unselectedBorder: toggleUnselectedBorder,
  unselectedContent: toggleUnselectedContent,
  unselectedDefault: toggleUnselectedDefault,
  unselectedHover: toggleUnselectedHover,
};

export const colors = {
  action: actionColors,
  background: backgroundColors,
  border: borderColors,
  custom: customColors,
  disabled: disabledColors,
  emotion: emotionColors,
  focus: focusColors,
  formField: formFieldColors,
  gradient: gradientColors,
  header: headerColors,
  neutral: neutralColors,
  selected: selectedColors,
  shadow: shadowColors,
  text: textColors,
  toggle: toggleColors,
};
