/* This file was generated by Supernova, don't change manually */
export const backgroundBackdrop = '#1a1b1b80';

export const backgroundInteractiveStateActive = '#f1edff';
export const backgroundInteractiveStateDefault = '#fff0';
export const backgroundInteractiveStateHover = '#f8f6ff';

export const backgroundPrimary = '#fff';
export const backgroundSecondary = '#f2f2f2';
export const backgroundTertiary = '#f1edff';

export const borderBasic = '#d9d9d9';
export const borderFocus = '#7847ff';

export const borderInteractiveStateActive = '#a5a5a5';
export const borderInteractiveStateDefault = '#bfbfbf';
export const borderInteractiveStateHover = '#b2b2b2';
export const borderInteractiveStateSelected = '#7847ff';

export const componentButtonPlainBorder = '#fff0';
export const componentButtonPlainContent = '#6039cc';
export const componentButtonPlainStateActive = '#e4daff';
export const componentButtonPlainStateDefault = '#fff0';
export const componentButtonPlainStateHover = '#f1edff';

export const componentButtonPrimaryBorder = '#4e2ea6';
export const componentButtonPrimaryContent = '#fff';
export const componentButtonPrimaryStateActive = '#6039cc';
export const componentButtonPrimaryStateDefault = '#7847ff';
export const componentButtonPrimaryStateHover = '#6c40e5';

export const componentButtonSecondaryBorder = '#7847ff';
export const componentButtonSecondaryContent = '#6039cc';
export const componentButtonSecondaryStateActive = '#e4daff';
export const componentButtonSecondaryStateDefault = '#fff';
export const componentButtonSecondaryStateHover = '#f1edff';

export const componentButtonTertiaryBorder = '#e5e5e5';
export const componentButtonTertiaryContent = '#202020';
export const componentButtonTertiaryStateActive = '#d9d9d9';
export const componentButtonTertiaryStateDefault = '#f2f2f2';
export const componentButtonTertiaryStateHover = '#e5e5e5';

export const componentHeaderBackground = '#fff';
export const componentHeaderItemBackgroundStateActive = '#f1edff';
export const componentHeaderItemBackgroundStateDefault = '#fff0';
export const componentHeaderItemBackgroundStateHover = '#f8f6ff';
export const componentHeaderItemBackgroundStateSelected = '#fff0';
export const componentHeaderItemStateActive = '#4e2ea6';
export const componentHeaderItemStateDefault = '#404040';
export const componentHeaderItemStateHover = '#6039cc';
export const componentHeaderItemStateSelected = '#6039cc';
export const componentHeaderStripeStateSelected = '#ffbe00';
export const componentHeaderStripeStateUnselected = '#e4daff';

export const componentToggleSelectedBorder = '#327c3f';
export const componentToggleSelectedContent = '#fff';
export const componentToggleSelectedStateActive = '#3e9b4f';
export const componentToggleSelectedStateDefault = '#327c3f';
export const componentToggleSelectedStateHover = '#388b47';
export const componentToggleUnselectedBorder = '#a5a5a5';
export const componentToggleUnselectedContent = '#404040';
export const componentToggleUnselectedStateActive = '#f2f2f2';
export const componentToggleUnselectedStateDefault = '#fff';
export const componentToggleUnselectedStateHover = '#f9f9f9';

export const disabledBackground = '#f9f9f9';
export const disabledBorder = '#e5e5e5';
export const disabledContent = '#a5a5a5';
export const disabledForeground = '#d9d9d9';

export const emotionDangerBackgroundBasic = '#b60000';
export const emotionDangerBackgroundSubtle = '#fef2f2';
export const emotionDangerBorderBasic = '#b60000';
export const emotionDangerBorderSubtle = '#f18080';
export const emotionDangerContentBasic = '#940000';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerStateActive = '#e40000';
export const emotionDangerStateDefault = '#b60000';
export const emotionDangerStateHover = '#cd0000';

export const emotionInformativeBackgroundBasic = '#0052ad';
export const emotionInformativeBackgroundSubtle = '#f2f7fd';
export const emotionInformativeBorderBasic = '#0052ad';
export const emotionInformativeBorderSubtle = '#80b2eb';
export const emotionInformativeContentBasic = '#00428c';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeStateActive = '#0066d8';
export const emotionInformativeStateDefault = '#0052ad';
export const emotionInformativeStateHover = '#005cc2';

export const emotionSuccessBackgroundBasic = '#327c3f';
export const emotionSuccessBackgroundSubtle = '#f5faf6';
export const emotionSuccessBorderBasic = '#327c3f';
export const emotionSuccessBorderSubtle = '#9ecda7';
export const emotionSuccessContentBasic = '#286533';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessStateActive = '#3e9b4f';
export const emotionSuccessStateDefault = '#327c3f';
export const emotionSuccessStateHover = '#388b47';

export const emotionWarningBackgroundBasic = '#c26400';
export const emotionWarningBackgroundSubtle = '#fef8f2';
export const emotionWarningBorderBasic = '#c26400';
export const emotionWarningBorderSubtle = '#f9be80';
export const emotionWarningContentBasic = '#9d5100';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningStateActive = '#f27d00';
export const emotionWarningStateDefault = '#c26400';
export const emotionWarningStateHover = '#da7100';

export const focusFocusRingColor01 = '#d2c2ffb2';

export const formFieldDanger = '#b60000';

export const formFieldFilledBackgroundStateActive = '#fff';
export const formFieldFilledBackgroundStateDefault = '#fff';
export const formFieldFilledBackgroundStateHover = '#f9f9f9';
export const formFieldFilledBorderStateActive = '#7f7f7f';
export const formFieldFilledBorderStateDefault = '#a5a5a5';
export const formFieldFilledBorderStateHover = '#999';
export const formFieldFilledBorderStateSelected = '#7847ff';
export const formFieldFilledContent = '#202020';
export const formFieldFilledPlaceholder = '#666';

export const formFieldHelperText = '#7f7f7f';
export const formFieldLabel = '#202020';
export const formFieldSuccess = '#327c3f';
export const formFieldWarning = '#c26400';

export const gradientBasicOverlayColor01 = '#fff';
export const gradientBasicOverlayColor02 = '#fff0';

export const lightDefaultAlphaDark0 = '#1a1b1b00';
export const lightDefaultAlphaDark100 = '#1a1b1b0d';
export const lightDefaultAlphaDark1000 = '#1a1b1b80';
export const lightDefaultAlphaDark200 = '#1a1b1b1a';
export const lightDefaultAlphaDark300 = '#1a1b1b26';
export const lightDefaultAlphaDark400 = '#1a1b1b33';
export const lightDefaultAlphaDark500 = '#1a1b1b40';
export const lightDefaultAlphaDark600 = '#1a1b1b4d';
export const lightDefaultAlphaDark700 = '#1a1b1b59';
export const lightDefaultAlphaDark800 = '#1a1b1b66';
export const lightDefaultAlphaDark900 = '#1a1b1b73';

export const lightDefaultAlphaLight0 = '#fff0';
export const lightDefaultAlphaLight100 = '#ffffff0d';
export const lightDefaultAlphaLight1000 = '#ffffff80';
export const lightDefaultAlphaLight200 = '#ffffff1a';
export const lightDefaultAlphaLight300 = '#ffffff26';
export const lightDefaultAlphaLight400 = '#fff3';
export const lightDefaultAlphaLight500 = '#ffffff40';
export const lightDefaultAlphaLight600 = '#ffffff4d';
export const lightDefaultAlphaLight700 = '#ffffff59';
export const lightDefaultAlphaLight800 = '#fff6';
export const lightDefaultAlphaLight900 = '#ffffff73';

export const lightDefaultBlack = '#000';

export const lightDefaultBlue100 = '#f2f7fd';
export const lightDefaultBlue1000 = '#0066d8';
export const lightDefaultBlue1100 = '#005cc2';
export const lightDefaultBlue1200 = '#0052ad';
export const lightDefaultBlue1300 = '#00428c';
export const lightDefaultBlue1400 = '#00336c';
export const lightDefaultBlue1500 = '#001a36';
export const lightDefaultBlue200 = '#e5f0fb';
export const lightDefaultBlue300 = '#cce0f7';
export const lightDefaultBlue400 = '#b2d1f3';
export const lightDefaultBlue500 = '#99c2ef';
export const lightDefaultBlue600 = '#80b2eb';
export const lightDefaultBlue700 = '#66a3e8';
export const lightDefaultBlue800 = '#4d94e4';
export const lightDefaultBlue900 = '#3385e0';

export const lightDefaultCloudy100 = '#f9f9f9';
export const lightDefaultCloudy1000 = '#7f7f7f';
export const lightDefaultCloudy1100 = '#727272';
export const lightDefaultCloudy1200 = '#666';
export const lightDefaultCloudy1300 = '#535353';
export const lightDefaultCloudy1400 = '#404040';
export const lightDefaultCloudy1500 = '#202020';
export const lightDefaultCloudy200 = '#f2f2f2';
export const lightDefaultCloudy300 = '#e5e5e5';
export const lightDefaultCloudy400 = '#d9d9d9';
export const lightDefaultCloudy500 = '#ccc';
export const lightDefaultCloudy600 = '#bfbfbf';
export const lightDefaultCloudy700 = '#b2b2b2';
export const lightDefaultCloudy800 = '#a5a5a5';
export const lightDefaultCloudy900 = '#999';

export const lightDefaultGreen100 = '#f5faf6';
export const lightDefaultGreen1000 = '#3e9b4f';
export const lightDefaultGreen1100 = '#388b47';
export const lightDefaultGreen1200 = '#327c3f';
export const lightDefaultGreen1300 = '#286533';
export const lightDefaultGreen1400 = '#1f4e28';
export const lightDefaultGreen1500 = '#102714';
export const lightDefaultGreen200 = '#ecf5ed';
export const lightDefaultGreen300 = '#d8ebdc';
export const lightDefaultGreen400 = '#c5e1ca';
export const lightDefaultGreen500 = '#b2d7b9';
export const lightDefaultGreen600 = '#9ecda7';
export const lightDefaultGreen700 = '#8bc395';
export const lightDefaultGreen800 = '#78b984';
export const lightDefaultGreen900 = '#65af72';

export const lightDefaultOrange100 = '#fef8f2';
export const lightDefaultOrange1000 = '#f27d00';
export const lightDefaultOrange1100 = '#da7100';
export const lightDefaultOrange1200 = '#c26400';
export const lightDefaultOrange1300 = '#9d5100';
export const lightDefaultOrange1400 = '#793f00';
export const lightDefaultOrange1500 = '#3d1f00';
export const lightDefaultOrange200 = '#fef2e5';
export const lightDefaultOrange300 = '#fce5cc';
export const lightDefaultOrange400 = '#fbd8b2';
export const lightDefaultOrange500 = '#facb99';
export const lightDefaultOrange600 = '#f9be80';
export const lightDefaultOrange700 = '#f7b166';
export const lightDefaultOrange800 = '#f6a44d';
export const lightDefaultOrange900 = '#f59733';

export const lightDefaultPurple100 = '#f8f6ff';
export const lightDefaultPurple1000 = '#7847ff';
export const lightDefaultPurple1100 = '#6c40e5';
export const lightDefaultPurple1200 = '#6039cc';
export const lightDefaultPurple1300 = '#4e2ea6';
export const lightDefaultPurple1400 = '#3c2480';
export const lightDefaultPurple1500 = '#1e1240';
export const lightDefaultPurple200 = '#f1edff';
export const lightDefaultPurple300 = '#e4daff';
export const lightDefaultPurple400 = '#d6c8ff';
export const lightDefaultPurple500 = '#c9b5ff';
export const lightDefaultPurple600 = '#bba3ff';
export const lightDefaultPurple700 = '#ae91ff';
export const lightDefaultPurple800 = '#a07eff';
export const lightDefaultPurple900 = '#936cff';

export const lightDefaultRed100 = '#fef2f2';
export const lightDefaultRed1000 = '#e40000';
export const lightDefaultRed1100 = '#cd0000';
export const lightDefaultRed1200 = '#b60000';
export const lightDefaultRed1300 = '#940000';
export const lightDefaultRed1400 = '#720000';
export const lightDefaultRed1500 = '#390000';
export const lightDefaultRed200 = '#fce5e5';
export const lightDefaultRed300 = '#facccc';
export const lightDefaultRed400 = '#f7b2b2';
export const lightDefaultRed500 = '#f49999';
export const lightDefaultRed600 = '#f18080';
export const lightDefaultRed700 = '#ef6666';
export const lightDefaultRed800 = '#ec4d4d';
export const lightDefaultRed900 = '#e93333';

export const lightDefaultWhite = '#fff';

export const lightDefaultYellow100 = '#fffcf2';
export const lightDefaultYellow1000 = '#ffbe00';
export const lightDefaultYellow1100 = '#e5ab00';
export const lightDefaultYellow1200 = '#cc9800';
export const lightDefaultYellow1300 = '#a67c00';
export const lightDefaultYellow1400 = '#805f00';
export const lightDefaultYellow1500 = '#403000';
export const lightDefaultYellow200 = '#fff8e5';
export const lightDefaultYellow300 = '#fff2cc';
export const lightDefaultYellow400 = '#ffebb2';
export const lightDefaultYellow500 = '#ffe599';
export const lightDefaultYellow600 = '#ffdf80';
export const lightDefaultYellow700 = '#ffd866';
export const lightDefaultYellow800 = '#ffd24d';
export const lightDefaultYellow900 = '#ffcb33';

export const lightOnBrandAlphaDark0 = '#1a1b1b00';
export const lightOnBrandAlphaDark100 = '#1a1b1b0d';
export const lightOnBrandAlphaDark1000 = '#1a1b1b80';
export const lightOnBrandAlphaDark200 = '#1a1b1b1a';
export const lightOnBrandAlphaDark300 = '#1a1b1b26';
export const lightOnBrandAlphaDark400 = '#1a1b1b33';
export const lightOnBrandAlphaDark500 = '#1a1b1b40';
export const lightOnBrandAlphaDark600 = '#1a1b1b4d';
export const lightOnBrandAlphaDark700 = '#1a1b1b59';
export const lightOnBrandAlphaDark800 = '#1a1b1b66';
export const lightOnBrandAlphaDark900 = '#1a1b1b73';

export const lightOnBrandAlphaLight0 = '#fff0';
export const lightOnBrandAlphaLight100 = '#ffffff0d';
export const lightOnBrandAlphaLight1000 = '#ffffff80';
export const lightOnBrandAlphaLight200 = '#ffffff1a';
export const lightOnBrandAlphaLight300 = '#ffffff26';
export const lightOnBrandAlphaLight400 = '#fff3';
export const lightOnBrandAlphaLight500 = '#ffffff40';
export const lightOnBrandAlphaLight600 = '#ffffff4d';
export const lightOnBrandAlphaLight700 = '#ffffff59';
export const lightOnBrandAlphaLight800 = '#fff6';
export const lightOnBrandAlphaLight900 = '#ffffff73';

export const lightOnBrandBlack = '#000';

export const lightOnBrandBlue100 = '#f2f7fd';
export const lightOnBrandBlue1000 = '#0066d8';
export const lightOnBrandBlue1100 = '#005cc2';
export const lightOnBrandBlue1200 = '#0052ad';
export const lightOnBrandBlue1300 = '#00428c';
export const lightOnBrandBlue1400 = '#00336c';
export const lightOnBrandBlue1500 = '#001a36';
export const lightOnBrandBlue200 = '#e5f0fb';
export const lightOnBrandBlue300 = '#cce0f7';
export const lightOnBrandBlue400 = '#b2d1f3';
export const lightOnBrandBlue500 = '#99c2ef';
export const lightOnBrandBlue600 = '#80b2eb';
export const lightOnBrandBlue700 = '#66a3e8';
export const lightOnBrandBlue800 = '#4d94e4';
export const lightOnBrandBlue900 = '#3385e0';

export const lightOnBrandCloudy100 = '#f9f9f9';
export const lightOnBrandCloudy1000 = '#7f7f7f';
export const lightOnBrandCloudy1100 = '#727272';
export const lightOnBrandCloudy1200 = '#666';
export const lightOnBrandCloudy1300 = '#535353';
export const lightOnBrandCloudy1400 = '#404040';
export const lightOnBrandCloudy1500 = '#202020';
export const lightOnBrandCloudy200 = '#f2f2f2';
export const lightOnBrandCloudy300 = '#e5e5e5';
export const lightOnBrandCloudy400 = '#d9d9d9';
export const lightOnBrandCloudy500 = '#ccc';
export const lightOnBrandCloudy600 = '#bfbfbf';
export const lightOnBrandCloudy700 = '#b2b2b2';
export const lightOnBrandCloudy800 = '#a5a5a5';
export const lightOnBrandCloudy900 = '#999';

export const lightOnBrandGreen100 = '#f5faf6';
export const lightOnBrandGreen1000 = '#3e9b4f';
export const lightOnBrandGreen1100 = '#388b47';
export const lightOnBrandGreen1200 = '#327c3f';
export const lightOnBrandGreen1300 = '#286533';
export const lightOnBrandGreen1400 = '#1f4e28';
export const lightOnBrandGreen1500 = '#102714';
export const lightOnBrandGreen200 = '#ecf5ed';
export const lightOnBrandGreen300 = '#d8ebdc';
export const lightOnBrandGreen400 = '#c5e1ca';
export const lightOnBrandGreen500 = '#b2d7b9';
export const lightOnBrandGreen600 = '#9ecda7';
export const lightOnBrandGreen700 = '#8bc395';
export const lightOnBrandGreen800 = '#78b984';
export const lightOnBrandGreen900 = '#65af72';

export const lightOnBrandOrange100 = '#fef8f2';
export const lightOnBrandOrange1000 = '#f27d00';
export const lightOnBrandOrange1100 = '#da7100';
export const lightOnBrandOrange1200 = '#c26400';
export const lightOnBrandOrange1300 = '#9d5100';
export const lightOnBrandOrange1400 = '#793f00';
export const lightOnBrandOrange1500 = '#3d1f00';
export const lightOnBrandOrange200 = '#fef2e5';
export const lightOnBrandOrange300 = '#fce5cc';
export const lightOnBrandOrange400 = '#fbd8b2';
export const lightOnBrandOrange500 = '#facb99';
export const lightOnBrandOrange600 = '#f9be80';
export const lightOnBrandOrange700 = '#f7b166';
export const lightOnBrandOrange800 = '#f6a44d';
export const lightOnBrandOrange900 = '#f59733';

export const lightOnBrandPurple100 = '#f8f6ff';
export const lightOnBrandPurple1000 = '#7847ff';
export const lightOnBrandPurple1100 = '#6c40e5';
export const lightOnBrandPurple1200 = '#6039cc';
export const lightOnBrandPurple1300 = '#4e2ea6';
export const lightOnBrandPurple1400 = '#3c2480';
export const lightOnBrandPurple1500 = '#1e1240';
export const lightOnBrandPurple200 = '#f1edff';
export const lightOnBrandPurple300 = '#e4daff';
export const lightOnBrandPurple400 = '#d6c8ff';
export const lightOnBrandPurple500 = '#c9b5ff';
export const lightOnBrandPurple600 = '#bba3ff';
export const lightOnBrandPurple700 = '#ae91ff';
export const lightOnBrandPurple800 = '#a07eff';
export const lightOnBrandPurple900 = '#936cff';

export const lightOnBrandRed100 = '#fef2f2';
export const lightOnBrandRed1000 = '#e40000';
export const lightOnBrandRed1100 = '#cd0000';
export const lightOnBrandRed1200 = '#b60000';
export const lightOnBrandRed1300 = '#940000';
export const lightOnBrandRed1400 = '#720000';
export const lightOnBrandRed1500 = '#390000';
export const lightOnBrandRed200 = '#fce5e5';
export const lightOnBrandRed300 = '#facccc';
export const lightOnBrandRed400 = '#f7b2b2';
export const lightOnBrandRed500 = '#f49999';
export const lightOnBrandRed600 = '#f18080';
export const lightOnBrandRed700 = '#ef6666';
export const lightOnBrandRed800 = '#ec4d4d';
export const lightOnBrandRed900 = '#e93333';

export const lightOnBrandWhite = '#fff';

export const lightOnBrandYellow100 = '#fffcf2';
export const lightOnBrandYellow1000 = '#ffbe00';
export const lightOnBrandYellow1100 = '#e5ab00';
export const lightOnBrandYellow1200 = '#cc9800';
export const lightOnBrandYellow1300 = '#a67c00';
export const lightOnBrandYellow1400 = '#805f00';
export const lightOnBrandYellow1500 = '#403000';
export const lightOnBrandYellow200 = '#fff8e5';
export const lightOnBrandYellow300 = '#fff2cc';
export const lightOnBrandYellow400 = '#ffebb2';
export const lightOnBrandYellow500 = '#ffe599';
export const lightOnBrandYellow600 = '#ffdf80';
export const lightOnBrandYellow700 = '#ffd866';
export const lightOnBrandYellow800 = '#ffd24d';
export const lightOnBrandYellow900 = '#ffcb33';

export const linkPrimaryStateActive = '#3c2480';
export const linkPrimaryStateDefault = '#6039cc';
export const linkPrimaryStateHover = '#4e2ea6';

export const linkSecondaryStateActive = '#3c2480';
export const linkSecondaryStateDefault = '#535353';
export const linkSecondaryStateHover = '#4e2ea6';

export const linkStateVisited = '#3c2480';

export const linkTertiaryStateActive = '#3c2480';
export const linkTertiaryStateDefault = '#7f7f7f';
export const linkTertiaryStateHover = '#4e2ea6';

export const neutralBackgroundBasic = '#202020';
export const neutralBackgroundSubtle = '#f2f2f2';
export const neutralBorderBasic = '#202020';
export const neutralBorderSubtle = '#bfbfbf';
export const neutralContentBasic = '#202020';
export const neutralContentSubtle = '#fff';
export const neutralStateActive = '#535353';
export const neutralStateDefault = '#202020';
export const neutralStateHover = '#404040';

export const selectedContentBasic = '#4e2ea6';
export const selectedContentSubtle = '#fff';
export const selectedStateActive = '#6039cc';
export const selectedStateDefault = '#7847ff';
export const selectedStateHover = '#6c40e5';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#202020';
export const textSecondary = '#535353';
export const textTertiary = '#7f7f7f';

export const backgroundColors = {
  backdrop: backgroundBackdrop,
  interactive: {
    stateActive: backgroundInteractiveStateActive,
    stateDefault: backgroundInteractiveStateDefault,
    stateHover: backgroundInteractiveStateHover,
  },
  primary: backgroundPrimary,
  secondary: backgroundSecondary,
  tertiary: backgroundTertiary,
};

export const borderColors = {
  basic: borderBasic,
  focus: borderFocus,
  interactive: {
    stateActive: borderInteractiveStateActive,
    stateDefault: borderInteractiveStateDefault,
    stateHover: borderInteractiveStateHover,
    stateSelected: borderInteractiveStateSelected,
  },
};

export const componentColors = {
  button: {
    plain: {
      border: componentButtonPlainBorder,
      content: componentButtonPlainContent,
      stateActive: componentButtonPlainStateActive,
      stateDefault: componentButtonPlainStateDefault,
      stateHover: componentButtonPlainStateHover,
    },
    primary: {
      border: componentButtonPrimaryBorder,
      content: componentButtonPrimaryContent,
      stateActive: componentButtonPrimaryStateActive,
      stateDefault: componentButtonPrimaryStateDefault,
      stateHover: componentButtonPrimaryStateHover,
    },
    secondary: {
      border: componentButtonSecondaryBorder,
      content: componentButtonSecondaryContent,
      stateActive: componentButtonSecondaryStateActive,
      stateDefault: componentButtonSecondaryStateDefault,
      stateHover: componentButtonSecondaryStateHover,
    },
    tertiary: {
      border: componentButtonTertiaryBorder,
      content: componentButtonTertiaryContent,
      stateActive: componentButtonTertiaryStateActive,
      stateDefault: componentButtonTertiaryStateDefault,
      stateHover: componentButtonTertiaryStateHover,
    },
  },
  header: {
    background: componentHeaderBackground,
    itemBackgroundStateActive: componentHeaderItemBackgroundStateActive,
    itemBackgroundStateDefault: componentHeaderItemBackgroundStateDefault,
    itemBackgroundStateHover: componentHeaderItemBackgroundStateHover,
    itemBackgroundStateSelected: componentHeaderItemBackgroundStateSelected,
    itemStateActive: componentHeaderItemStateActive,
    itemStateDefault: componentHeaderItemStateDefault,
    itemStateHover: componentHeaderItemStateHover,
    itemStateSelected: componentHeaderItemStateSelected,
    stripeStateSelected: componentHeaderStripeStateSelected,
    stripeStateUnselected: componentHeaderStripeStateUnselected,
  },
  toggle: {
    selectedBorder: componentToggleSelectedBorder,
    selectedContent: componentToggleSelectedContent,
    selectedStateActive: componentToggleSelectedStateActive,
    selectedStateDefault: componentToggleSelectedStateDefault,
    selectedStateHover: componentToggleSelectedStateHover,
    unselectedBorder: componentToggleUnselectedBorder,
    unselectedContent: componentToggleUnselectedContent,
    unselectedStateActive: componentToggleUnselectedStateActive,
    unselectedStateDefault: componentToggleUnselectedStateDefault,
    unselectedStateHover: componentToggleUnselectedStateHover,
  },
};

export const disabledColors = {
  background: disabledBackground,
  border: disabledBorder,
  content: disabledContent,
  foreground: disabledForeground,
};

export const emotionColors = {
  danger: {
    backgroundBasic: emotionDangerBackgroundBasic,
    backgroundSubtle: emotionDangerBackgroundSubtle,
    borderBasic: emotionDangerBorderBasic,
    borderSubtle: emotionDangerBorderSubtle,
    contentBasic: emotionDangerContentBasic,
    contentSubtle: emotionDangerContentSubtle,
    stateActive: emotionDangerStateActive,
    stateDefault: emotionDangerStateDefault,
    stateHover: emotionDangerStateHover,
  },
  informative: {
    backgroundBasic: emotionInformativeBackgroundBasic,
    backgroundSubtle: emotionInformativeBackgroundSubtle,
    borderBasic: emotionInformativeBorderBasic,
    borderSubtle: emotionInformativeBorderSubtle,
    contentBasic: emotionInformativeContentBasic,
    contentSubtle: emotionInformativeContentSubtle,
    stateActive: emotionInformativeStateActive,
    stateDefault: emotionInformativeStateDefault,
    stateHover: emotionInformativeStateHover,
  },
  success: {
    backgroundBasic: emotionSuccessBackgroundBasic,
    backgroundSubtle: emotionSuccessBackgroundSubtle,
    borderBasic: emotionSuccessBorderBasic,
    borderSubtle: emotionSuccessBorderSubtle,
    contentBasic: emotionSuccessContentBasic,
    contentSubtle: emotionSuccessContentSubtle,
    stateActive: emotionSuccessStateActive,
    stateDefault: emotionSuccessStateDefault,
    stateHover: emotionSuccessStateHover,
  },
  warning: {
    backgroundBasic: emotionWarningBackgroundBasic,
    backgroundSubtle: emotionWarningBackgroundSubtle,
    borderBasic: emotionWarningBorderBasic,
    borderSubtle: emotionWarningBorderSubtle,
    contentBasic: emotionWarningContentBasic,
    contentSubtle: emotionWarningContentSubtle,
    stateActive: emotionWarningStateActive,
    stateDefault: emotionWarningStateDefault,
    stateHover: emotionWarningStateHover,
  },
};

export const focusColors = {
  focusRing: {
    color01: focusFocusRingColor01,
  },
};

export const formFieldColors = {
  danger: formFieldDanger,
  filled: {
    backgroundStateActive: formFieldFilledBackgroundStateActive,
    backgroundStateDefault: formFieldFilledBackgroundStateDefault,
    backgroundStateHover: formFieldFilledBackgroundStateHover,
    borderStateActive: formFieldFilledBorderStateActive,
    borderStateDefault: formFieldFilledBorderStateDefault,
    borderStateHover: formFieldFilledBorderStateHover,
    borderStateSelected: formFieldFilledBorderStateSelected,
    content: formFieldFilledContent,
    placeholder: formFieldFilledPlaceholder,
  },
  helperText: formFieldHelperText,
  label: formFieldLabel,
  success: formFieldSuccess,
  warning: formFieldWarning,
};

export const gradientColors = {
  basicOverlay: {
    color02: gradientBasicOverlayColor02,
  },
};

export const lightDefaultColors = {
  alphaDark: {
    _900: lightDefaultAlphaDark900,
  },
  alphaLight: {
    _900: lightDefaultAlphaLight900,
  },
  black: lightDefaultBlack,
  blue: {
    _100: lightDefaultBlue100,
    _1000: lightDefaultBlue1000,
    _1100: lightDefaultBlue1100,
    _1200: lightDefaultBlue1200,
    _1300: lightDefaultBlue1300,
    _1400: lightDefaultBlue1400,
    _1500: lightDefaultBlue1500,
    _200: lightDefaultBlue200,
    _300: lightDefaultBlue300,
    _400: lightDefaultBlue400,
    _500: lightDefaultBlue500,
    _600: lightDefaultBlue600,
    _700: lightDefaultBlue700,
    _800: lightDefaultBlue800,
    _900: lightDefaultBlue900,
  },
  cloudy: {
    _100: lightDefaultCloudy100,
    _1000: lightDefaultCloudy1000,
    _1100: lightDefaultCloudy1100,
    _1200: lightDefaultCloudy1200,
    _1300: lightDefaultCloudy1300,
    _1400: lightDefaultCloudy1400,
    _1500: lightDefaultCloudy1500,
    _200: lightDefaultCloudy200,
    _300: lightDefaultCloudy300,
    _400: lightDefaultCloudy400,
    _500: lightDefaultCloudy500,
    _600: lightDefaultCloudy600,
    _700: lightDefaultCloudy700,
    _800: lightDefaultCloudy800,
    _900: lightDefaultCloudy900,
  },
  green: {
    _100: lightDefaultGreen100,
    _1000: lightDefaultGreen1000,
    _1100: lightDefaultGreen1100,
    _1200: lightDefaultGreen1200,
    _1300: lightDefaultGreen1300,
    _1400: lightDefaultGreen1400,
    _1500: lightDefaultGreen1500,
    _200: lightDefaultGreen200,
    _300: lightDefaultGreen300,
    _400: lightDefaultGreen400,
    _500: lightDefaultGreen500,
    _600: lightDefaultGreen600,
    _700: lightDefaultGreen700,
    _800: lightDefaultGreen800,
    _900: lightDefaultGreen900,
  },
  orange: {
    _100: lightDefaultOrange100,
    _1000: lightDefaultOrange1000,
    _1100: lightDefaultOrange1100,
    _1200: lightDefaultOrange1200,
    _1300: lightDefaultOrange1300,
    _1400: lightDefaultOrange1400,
    _1500: lightDefaultOrange1500,
    _200: lightDefaultOrange200,
    _300: lightDefaultOrange300,
    _400: lightDefaultOrange400,
    _500: lightDefaultOrange500,
    _600: lightDefaultOrange600,
    _700: lightDefaultOrange700,
    _800: lightDefaultOrange800,
    _900: lightDefaultOrange900,
  },
  purple: {
    _100: lightDefaultPurple100,
    _1000: lightDefaultPurple1000,
    _1100: lightDefaultPurple1100,
    _1200: lightDefaultPurple1200,
    _1300: lightDefaultPurple1300,
    _1400: lightDefaultPurple1400,
    _1500: lightDefaultPurple1500,
    _200: lightDefaultPurple200,
    _300: lightDefaultPurple300,
    _400: lightDefaultPurple400,
    _500: lightDefaultPurple500,
    _600: lightDefaultPurple600,
    _700: lightDefaultPurple700,
    _800: lightDefaultPurple800,
    _900: lightDefaultPurple900,
  },
  red: {
    _100: lightDefaultRed100,
    _1000: lightDefaultRed1000,
    _1100: lightDefaultRed1100,
    _1200: lightDefaultRed1200,
    _1300: lightDefaultRed1300,
    _1400: lightDefaultRed1400,
    _1500: lightDefaultRed1500,
    _200: lightDefaultRed200,
    _300: lightDefaultRed300,
    _400: lightDefaultRed400,
    _500: lightDefaultRed500,
    _600: lightDefaultRed600,
    _700: lightDefaultRed700,
    _800: lightDefaultRed800,
    _900: lightDefaultRed900,
  },
  white: lightDefaultWhite,
  yellow: {
    _100: lightDefaultYellow100,
    _1000: lightDefaultYellow1000,
    _1100: lightDefaultYellow1100,
    _1200: lightDefaultYellow1200,
    _1300: lightDefaultYellow1300,
    _1400: lightDefaultYellow1400,
    _1500: lightDefaultYellow1500,
    _200: lightDefaultYellow200,
    _300: lightDefaultYellow300,
    _400: lightDefaultYellow400,
    _500: lightDefaultYellow500,
    _600: lightDefaultYellow600,
    _700: lightDefaultYellow700,
    _800: lightDefaultYellow800,
    _900: lightDefaultYellow900,
  },
};

export const lightOnBrandColors = {
  alphaDark: {
    _900: lightOnBrandAlphaDark900,
  },
  alphaLight: {
    _900: lightOnBrandAlphaLight900,
  },
  black: lightOnBrandBlack,
  blue: {
    _100: lightOnBrandBlue100,
    _1000: lightOnBrandBlue1000,
    _1100: lightOnBrandBlue1100,
    _1200: lightOnBrandBlue1200,
    _1300: lightOnBrandBlue1300,
    _1400: lightOnBrandBlue1400,
    _1500: lightOnBrandBlue1500,
    _200: lightOnBrandBlue200,
    _300: lightOnBrandBlue300,
    _400: lightOnBrandBlue400,
    _500: lightOnBrandBlue500,
    _600: lightOnBrandBlue600,
    _700: lightOnBrandBlue700,
    _800: lightOnBrandBlue800,
    _900: lightOnBrandBlue900,
  },
  cloudy: {
    _100: lightOnBrandCloudy100,
    _1000: lightOnBrandCloudy1000,
    _1100: lightOnBrandCloudy1100,
    _1200: lightOnBrandCloudy1200,
    _1300: lightOnBrandCloudy1300,
    _1400: lightOnBrandCloudy1400,
    _1500: lightOnBrandCloudy1500,
    _200: lightOnBrandCloudy200,
    _300: lightOnBrandCloudy300,
    _400: lightOnBrandCloudy400,
    _500: lightOnBrandCloudy500,
    _600: lightOnBrandCloudy600,
    _700: lightOnBrandCloudy700,
    _800: lightOnBrandCloudy800,
    _900: lightOnBrandCloudy900,
  },
  green: {
    _100: lightOnBrandGreen100,
    _1000: lightOnBrandGreen1000,
    _1100: lightOnBrandGreen1100,
    _1200: lightOnBrandGreen1200,
    _1300: lightOnBrandGreen1300,
    _1400: lightOnBrandGreen1400,
    _1500: lightOnBrandGreen1500,
    _200: lightOnBrandGreen200,
    _300: lightOnBrandGreen300,
    _400: lightOnBrandGreen400,
    _500: lightOnBrandGreen500,
    _600: lightOnBrandGreen600,
    _700: lightOnBrandGreen700,
    _800: lightOnBrandGreen800,
    _900: lightOnBrandGreen900,
  },
  orange: {
    _100: lightOnBrandOrange100,
    _1000: lightOnBrandOrange1000,
    _1100: lightOnBrandOrange1100,
    _1200: lightOnBrandOrange1200,
    _1300: lightOnBrandOrange1300,
    _1400: lightOnBrandOrange1400,
    _1500: lightOnBrandOrange1500,
    _200: lightOnBrandOrange200,
    _300: lightOnBrandOrange300,
    _400: lightOnBrandOrange400,
    _500: lightOnBrandOrange500,
    _600: lightOnBrandOrange600,
    _700: lightOnBrandOrange700,
    _800: lightOnBrandOrange800,
    _900: lightOnBrandOrange900,
  },
  purple: {
    _100: lightOnBrandPurple100,
    _1000: lightOnBrandPurple1000,
    _1100: lightOnBrandPurple1100,
    _1200: lightOnBrandPurple1200,
    _1300: lightOnBrandPurple1300,
    _1400: lightOnBrandPurple1400,
    _1500: lightOnBrandPurple1500,
    _200: lightOnBrandPurple200,
    _300: lightOnBrandPurple300,
    _400: lightOnBrandPurple400,
    _500: lightOnBrandPurple500,
    _600: lightOnBrandPurple600,
    _700: lightOnBrandPurple700,
    _800: lightOnBrandPurple800,
    _900: lightOnBrandPurple900,
  },
  red: {
    _100: lightOnBrandRed100,
    _1000: lightOnBrandRed1000,
    _1100: lightOnBrandRed1100,
    _1200: lightOnBrandRed1200,
    _1300: lightOnBrandRed1300,
    _1400: lightOnBrandRed1400,
    _1500: lightOnBrandRed1500,
    _200: lightOnBrandRed200,
    _300: lightOnBrandRed300,
    _400: lightOnBrandRed400,
    _500: lightOnBrandRed500,
    _600: lightOnBrandRed600,
    _700: lightOnBrandRed700,
    _800: lightOnBrandRed800,
    _900: lightOnBrandRed900,
  },
  white: lightOnBrandWhite,
  yellow: {
    _100: lightOnBrandYellow100,
    _1000: lightOnBrandYellow1000,
    _1100: lightOnBrandYellow1100,
    _1200: lightOnBrandYellow1200,
    _1300: lightOnBrandYellow1300,
    _1400: lightOnBrandYellow1400,
    _1500: lightOnBrandYellow1500,
    _200: lightOnBrandYellow200,
    _300: lightOnBrandYellow300,
    _400: lightOnBrandYellow400,
    _500: lightOnBrandYellow500,
    _600: lightOnBrandYellow600,
    _700: lightOnBrandYellow700,
    _800: lightOnBrandYellow800,
    _900: lightOnBrandYellow900,
  },
};

export const linkColors = {
  primary: {
    stateActive: linkPrimaryStateActive,
    stateDefault: linkPrimaryStateDefault,
    stateHover: linkPrimaryStateHover,
  },
  secondary: {
    stateActive: linkSecondaryStateActive,
    stateDefault: linkSecondaryStateDefault,
    stateHover: linkSecondaryStateHover,
  },
  stateVisited: linkStateVisited,
  tertiary: {
    stateActive: linkTertiaryStateActive,
    stateDefault: linkTertiaryStateDefault,
    stateHover: linkTertiaryStateHover,
  },
};

export const neutralColors = {
  backgroundBasic: neutralBackgroundBasic,
  backgroundSubtle: neutralBackgroundSubtle,
  borderBasic: neutralBorderBasic,
  borderSubtle: neutralBorderSubtle,
  contentBasic: neutralContentBasic,
  contentSubtle: neutralContentSubtle,
  stateActive: neutralStateActive,
  stateDefault: neutralStateDefault,
  stateHover: neutralStateHover,
};

export const selectedColors = {
  contentBasic: selectedContentBasic,
  contentSubtle: selectedContentSubtle,
  stateActive: selectedStateActive,
  stateDefault: selectedStateDefault,
  stateHover: selectedStateHover,
};

export const shadowColors = {
  shadow100: {
    color01: shadowShadow100Color01,
  },
  shadow200: {
    color01: shadowShadow200Color01,
  },
  shadow300: {
    color01: shadowShadow300Color01,
  },
  shadow400: {
    color01: shadowShadow400Color01,
  },
};

export const textColors = {
  primary: textPrimary,
  secondary: textSecondary,
  tertiary: textTertiary,
};

export const colors = {
  background: backgroundColors,
  border: borderColors,
  component: componentColors,
  disabled: disabledColors,
  emotion: emotionColors,
  focus: focusColors,
  formField: formFieldColors,
  gradient: gradientColors,
  lightDefault: lightDefaultColors,
  lightOnBrand: lightOnBrandColors,
  link: linkColors,
  neutral: neutralColors,
  selected: selectedColors,
  shadow: shadowColors,
  text: textColors,
};
