/* This file was generated by Supernova, don't change manually */
export const backgroundBackdrop = '#1a1b1b80';

export const backgroundInteractiveStateActive = '#f1edff';
export const backgroundInteractiveStateDefault = '#fff0';
export const backgroundInteractiveStateHover = '#f8f6ff';

export const backgroundPrimary = '#fff';
export const backgroundSecondary = '#f2f2f2';
export const backgroundTertiary = '#f1edff';

export const borderBasic = '#d9d9d9';
export const borderFocus = '#7847ff';

export const borderInteractiveStateActive = '#a5a5a5';
export const borderInteractiveStateDefault = '#bfbfbf';
export const borderInteractiveStateHover = '#b2b2b2';
export const borderInteractiveStateSelected = '#7847ff';

export const componentButtonPlainBorder = '#fff0';
export const componentButtonPlainContent = '#6039cc';
export const componentButtonPlainStateActive = '#e4daff';
export const componentButtonPlainStateDefault = '#fff0';
export const componentButtonPlainStateHover = '#f1edff';

export const componentButtonPrimaryBorder = '#4e2ea6';
export const componentButtonPrimaryContent = '#fff';
export const componentButtonPrimaryStateActive = '#6039cc';
export const componentButtonPrimaryStateDefault = '#7847ff';
export const componentButtonPrimaryStateHover = '#6c40e5';

export const componentButtonSecondaryBorder = '#7847ff';
export const componentButtonSecondaryContent = '#6039cc';
export const componentButtonSecondaryStateActive = '#e4daff';
export const componentButtonSecondaryStateDefault = '#fff';
export const componentButtonSecondaryStateHover = '#f1edff';

export const componentButtonTertiaryBorder = '#e5e5e5';
export const componentButtonTertiaryContent = '#202020';
export const componentButtonTertiaryStateActive = '#d9d9d9';
export const componentButtonTertiaryStateDefault = '#f2f2f2';
export const componentButtonTertiaryStateHover = '#e5e5e5';

export const componentHeaderBackground = '#fff';
export const componentHeaderItemBackgroundStateActive = '#f1edff';
export const componentHeaderItemBackgroundStateDefault = '#fff0';
export const componentHeaderItemBackgroundStateHover = '#f8f6ff';
export const componentHeaderItemBackgroundStateSelected = '#fff0';
export const componentHeaderItemStateActive = '#4e2ea6';
export const componentHeaderItemStateDefault = '#404040';
export const componentHeaderItemStateHover = '#6039cc';
export const componentHeaderItemStateSelected = '#6039cc';
export const componentHeaderStripeStateSelected = '#ffbe00';
export const componentHeaderStripeStateUnselected = '#e4daff';

export const componentToggleSelectedBorder = '#327c3f';
export const componentToggleSelectedContent = '#fff';
export const componentToggleSelectedStateActive = '#3e9b4f';
export const componentToggleSelectedStateDefault = '#327c3f';
export const componentToggleSelectedStateHover = '#388b47';
export const componentToggleUnselectedBorder = '#a5a5a5';
export const componentToggleUnselectedContent = '#404040';
export const componentToggleUnselectedStateActive = '#f2f2f2';
export const componentToggleUnselectedStateDefault = '#fff';
export const componentToggleUnselectedStateHover = '#f9f9f9';

export const disabledBackground = '#f9f9f9';
export const disabledBorder = '#e5e5e5';
export const disabledContent = '#a5a5a5';
export const disabledForeground = '#d9d9d9';

export const emotionDangerBackgroundBasic = '#b60000';
export const emotionDangerBackgroundSubtle = '#fef2f2';
export const emotionDangerBorderBasic = '#b60000';
export const emotionDangerBorderSubtle = '#f18080';
export const emotionDangerContentBasic = '#940000';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerStateActive = '#e40000';
export const emotionDangerStateDefault = '#b60000';
export const emotionDangerStateHover = '#cd0000';

export const emotionInformativeBackgroundBasic = '#0052ad';
export const emotionInformativeBackgroundSubtle = '#f2f7fd';
export const emotionInformativeBorderBasic = '#0052ad';
export const emotionInformativeBorderSubtle = '#80b2eb';
export const emotionInformativeContentBasic = '#00428c';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeStateActive = '#0066d8';
export const emotionInformativeStateDefault = '#0052ad';
export const emotionInformativeStateHover = '#005cc2';

export const emotionSuccessBackgroundBasic = '#327c3f';
export const emotionSuccessBackgroundSubtle = '#f5faf6';
export const emotionSuccessBorderBasic = '#327c3f';
export const emotionSuccessBorderSubtle = '#9ecda7';
export const emotionSuccessContentBasic = '#286533';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessStateActive = '#3e9b4f';
export const emotionSuccessStateDefault = '#327c3f';
export const emotionSuccessStateHover = '#388b47';

export const emotionWarningBackgroundBasic = '#c26400';
export const emotionWarningBackgroundSubtle = '#fef8f2';
export const emotionWarningBorderBasic = '#c26400';
export const emotionWarningBorderSubtle = '#f9be80';
export const emotionWarningContentBasic = '#9d5100';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningStateActive = '#f27d00';
export const emotionWarningStateDefault = '#c26400';
export const emotionWarningStateHover = '#da7100';

export const focusFocusRingColor01 = '#d2c2ffb2';

export const formFieldDanger = '#b60000';

export const formFieldFilledBackgroundStateActive = '#fff';
export const formFieldFilledBackgroundStateDefault = '#fff';
export const formFieldFilledBackgroundStateHover = '#f9f9f9';
export const formFieldFilledBorderStateActive = '#7f7f7f';
export const formFieldFilledBorderStateDefault = '#a5a5a5';
export const formFieldFilledBorderStateHover = '#999';
export const formFieldFilledBorderStateSelected = '#7847ff';
export const formFieldFilledContent = '#202020';
export const formFieldFilledPlaceholder = '#666';

export const formFieldHelperText = '#7f7f7f';
export const formFieldLabel = '#202020';
export const formFieldSuccess = '#327c3f';
export const formFieldWarning = '#c26400';

export const gradientBasicOverlayColor01 = '#fff';
export const gradientBasicOverlayColor02 = '#fff0';

export const gradientSkeletonColor01 = '#e5e5e5';
export const gradientSkeletonColor02 = '#fff';
export const gradientSkeletonColor03 = '#e5e5e5';

export const linkPrimaryStateActive = '#3c2480';
export const linkPrimaryStateDefault = '#6039cc';
export const linkPrimaryStateHover = '#4e2ea6';

export const linkSecondaryStateActive = '#3c2480';
export const linkSecondaryStateDefault = '#535353';
export const linkSecondaryStateHover = '#4e2ea6';

export const linkStateVisited = '#3c2480';

export const linkTertiaryStateActive = '#3c2480';
export const linkTertiaryStateDefault = '#7f7f7f';
export const linkTertiaryStateHover = '#4e2ea6';

export const neutralBackgroundBasic = '#202020';
export const neutralBackgroundSubtle = '#f2f2f2';
export const neutralBorderBasic = '#202020';
export const neutralBorderSubtle = '#bfbfbf';
export const neutralContentBasic = '#202020';
export const neutralContentSubtle = '#fff';
export const neutralStateActive = '#535353';
export const neutralStateDefault = '#202020';
export const neutralStateHover = '#404040';

export const selectedContentBasic = '#4e2ea6';
export const selectedContentSubtle = '#fff';
export const selectedStateActive = '#6039cc';
export const selectedStateDefault = '#7847ff';
export const selectedStateHover = '#6c40e5';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#202020';
export const textSecondary = '#535353';
export const textTertiary = '#7f7f7f';
