FROM dcreg.service.consul/prod/compres-base-nodejs-14:1.0.0

LABEL maintainer="Tomas Litera <tomas.litera@lmc.eu>"

ARG NODE_ENV

RUN mkdir -p /lmc/spirit-design-system

WORKDIR /lmc/spirit-design-system
