BC: ['bc/*', 'break/*']
feature: ['feature/*', 'feat/*']
bug: ['fix/*', 'bugfix/*']
refactoring: ['refactor/*', 'refactoring/*']
documentation: ['docs/*', 'documentation/*']
maintenance: ['maintenance/*', 'chore/*']
