# Path where the downloaded packages are stored on your system.
# @see: https://yarnpkg.com/configuration/yarnrc#cacheFolder
cacheFolder: ./.yarn/cache

# Compression level employed for zip archives
# @see: https://yarnpkg.com/configuration/yarnrc#compressionLevel
compressionLevel: mixed

# Define whether the cache should be shared between all local projects.
# @see: https://yarnpkg.com/configuration/yarnrc#enableGlobalCache
enableGlobalCache: false

# Define whether anonymous telemetry data should be sent or not.
# @see: https://yarnpkg.com/configuration/yarnrc#enableTelemetry
enableTelemetry: false

# Define how Node packages should be installed.
# @see: https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules

# Do not run postinstall scripts from 3rd party packages
# @see: https://pnpm.io/supply-chain-security
# @see: https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false

# Reduce the likelihood of installing compromised packages
# @see: https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: '7d'

# Enable provenance publishing for npm packages
# @see: https://yarnpkg.com/configuration/yarnrc#npmPublishProvenance
npmPublishProvenance: true

# Catalogs provide centralized dependency version management for workspaces.
# @see: https://yarnpkg.com/features/catalogs
catalogs:
  # Core frontend framework dependencies
  frontend:
    next: 15.5.9
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.18
    '@types/react-dom': 18.3.5
    '@types/react-transition-group': 4.4.12
    classnames: ^2.3.1
    '@floating-ui/react': ^0.27.0
    '@floating-ui/dom': ^1.5.3
    react-transition-group: ^4.4.5
    '@csstools/normalize.css': ^12.0.0
  # Packages used for scripting tasks
  script:
    npm-run-all2: 6.2.6
    shx: 0.4.0
    rimraf: 5.0.10
    glob: 10.5.0
    tsx: 4.20.6
    ts-node: 10.9.2
    execa: ^9.0.0
    zx: ^8.0.0
    sade: ^1.8.1
    jscodeshift: ^17.0.0
    '@types/jscodeshift': ^0.12.0
    recast: 0.23.11
    filedirname: ^3.0.0
    lerna: 9.0.3
    nx: 22.2.0
    is-ci: 3.0.1
  # Packages used for building the project
  build:
    vite: 7.0.8
    rollup: 4.34.6
    webpack: 5.97.1
    webpack-cli: 5.1.4
    webpack-merge: 6.0.1
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-typescript': 12.1.4
    '@rollup/plugin-babel': 6.0.4
    '@rollup/plugin-node-resolve': 15.3.1
    '@rollup/plugin-replace': 6.0.2
    terser-webpack-plugin: 5.3.14
    vite-plugin-dts: 4.5.0
    '@vitejs/plugin-react': 4.7.0
    '@babel/core': 7.26.10
    '@babel/preset-react': 7.26.3
    '@babel/preset-env': 7.26.9
    '@babel/preset-typescript': 7.27.0
    '@types/babel__core': 7.20.5
    '@swc/core': 1.11.22
    ts-loader: 9.5.4
    tsup: 8.5.0
    tslib: 2.8.1
    sass: 1.93.2
    sass-embedded: 1.93.2
    postcss: 8.5.6
    postcss-cli: 11.0.1
    autoprefixer: 10.4.21
    clean-css-cli: 5.6.3
    '@lmc-eu/browserslist-config': 2.0.1
  # Testing frameworks and libraries
  testing:
    jest: 30.2.0
    jest-cli: 30.2.0
    jest-axe: 10.0.0
    jest-environment-jsdom: 30.2.0
    jest-environment-node-single-context: 29.4.0
    '@types/jest': 30.0.0
    '@types/jest-axe': 3.5.9
    '@playwright/test': 1.56.0
    '@axe-core/playwright': 4.11.0
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/dom': 10.4.1
    '@testing-library/react': 16.3.0
    '@testing-library/user-event': 14.6.1
    axe-core: 4.11.0
    resize-observer-polyfill: ^1.5.1
    '@juggle/resize-observer': 3.4.0
    '@swc/jest': 0.2.38
    '@babel/eslint-parser': ^7.19.1
    sass-true: 8.1.0

plugins:
  # Specify the desired Node version constraint using engines.node field
  # and the plugin will fail installation if the current Node version does not satisfy it
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
