# Path where the downloaded packages are stored on your system.
# @see: https://yarnpkg.com/configuration/yarnrc#cacheFolder
cacheFolder: ./.yarn/cache

# Compression level employed for zip archives
# @see: https://yarnpkg.com/configuration/yarnrc#compressionLevel
compressionLevel: mixed

# Define whether the cache should be shared between all local projects.
# @see: https://yarnpkg.com/configuration/yarnrc#enableGlobalCache
enableGlobalCache: false

# Define whether anonymous telemetry data should be sent or not.
# @see: https://yarnpkg.com/configuration/yarnrc#enableTelemetry
enableTelemetry: false

# Define how Node packages should be installed.
# @see: https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules

# Do not run postinstall scripts from 3rd party packages
# @see: https://pnpm.io/supply-chain-security
# @see: https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false

# Reduce the likelihood of installing compromised packages
# @see: https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: '7d'

# Enable provenance publishing for npm packages
# @see: https://yarnpkg.com/configuration/yarnrc#npmPublishProvenance
npmPublishProvenance: true

# Catalogs provide centralized dependency version management for workspaces.
# @see: https://yarnpkg.com/features/catalogs
catalogs:
  frontend:
    next: 15.5.8
    react: 19.0.0
    react-dom: 19.0.0

plugins:
  # Specify the desired Node version constraint using engines.node field
  # and the plugin will fail installation if the current Node version does not satisfy it
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
