/* This file was generated by Supernova, don't change manually */
export const gradientBasicOverlay = 'linear-gradient(var(--gradient-angle, 90deg), var(--spirit-color-gradient-basic-overlay-color-01, #fff) 0%, var(--spirit-color-gradient-basic-overlay-color-02, #fff0) 100%)';
export const gradientPrimary = 'linear-gradient(var(--gradient-angle, 180deg), var(--spirit-color-gradient-primary-color-01, #7847ff) 0%, var(--spirit-color-gradient-primary-color-02, #482b99) 100%)';
export const gradientSecondary = 'linear-gradient(var(--gradient-angle, 180deg), var(--spirit-color-gradient-secondary-color-01, #eae3ff) 0%, var(--spirit-color-gradient-secondary-color-02, #cebcff) 100%)';
export const gradientSkeleton = 'linear-gradient(var(--gradient-angle, 135deg), var(--spirit-color-gradient-skeleton-color-01, #e5e5e5) 33%, var(--spirit-color-gradient-skeleton-color-02, #fff) 48.5%, var(--spirit-color-gradient-skeleton-color-03, #e5e5e5) 66%)';

export const gradients = {
  basicOverlay: gradientBasicOverlay,
  primary: gradientPrimary,
  secondary: gradientSecondary,
  skeleton: gradientSkeleton,
};
