/* This file was generated by Supernova, don't change manually */
export const gradientBasicOverlay = 'linear-gradient(var(--gradient-angle, 90deg), var(--spirit-color-gradient-basic-overlay-color-01, #fff) 0%, var(--spirit-color-gradient-basic-overlay-color-02, #fff0) 100%)';

export const gradients = {
  basicOverlay: gradientBasicOverlay,
};
