/* This file was generated by Supernova, don't change manually */
export const containerPaddingMobile = '16px';
export const containerPaddingTablet = '32px';
export const containerPaddingDesktop = '32px';

export const containerXSmallMaxWidth = '480px';

export const containerSmallMaxWidth = '640px';

export const containerMediumMaxWidth = '768px';

export const containerLargeMaxWidth = '1024px';

export const containerMaxWidth = '1280px';

export const containerXLargeMaxWidth = '1280px';

export const breakpointMobile = 0;
export const breakpointTablet = '768px';
export const breakpointDesktop = '1280px';

export const gridSpacingMobile = '16px';
export const gridSpacingDesktop = '32px';
export const gridSpacingTablet = '32px';

export const gridColumns = '12';

export const cssVariablePrefix = 'spirit-';

export const containers = {
  padding: {
    mobile: containerPaddingMobile,
    tablet: containerPaddingTablet,
    desktop: containerPaddingDesktop,
  },
  xSmall: {
    maxWidth: containerXSmallMaxWidth,
  },
  small: {
    maxWidth: containerSmallMaxWidth,
  },
  medium: {
    maxWidth: containerMediumMaxWidth,
  },
  large: {
    maxWidth: containerLargeMaxWidth,
  },
  maxWidth: containerMaxWidth,
  xLarge: {
    maxWidth: containerXLargeMaxWidth,
  },
};

export const breakpoints = {
  mobile: breakpointMobile,
  tablet: breakpointTablet,
  desktop: breakpointDesktop,
};

export const grids = {
  spacing: {
    mobile: gridSpacingMobile,
    desktop: gridSpacingDesktop,
    tablet: gridSpacingTablet,
  },
  columns: gridColumns,
};
