/* This file was generated by Supernova, don't change manually */
export const radius0 = 0;
export const radius100 = '2px';
export const radius200 = '4px';
export const radius300 = '8px';
export const radius400 = '12px';
export const radius500 = '16px';
export const radiusFull = '9999px';

export const radii = {
  0: radius0,
  100: radius100,
  200: radius200,
  300: radius300,
  400: radius400,
  500: radius500,
  full: radiusFull,
};
