/* This file was generated by Supernova, don't change manually */
export const headingXlargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const headingLargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingMediumBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const headingSmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const headingXsmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const headingSmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingXsmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingXlargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingXlargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingXlargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingLargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingMediumRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingMediumSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingMediumItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingSmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingSmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingXsmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingXsmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const bodyXlargeLight = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyXlargeLightItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyXlargeMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyXlargeMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyXlargeSemiboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyXlargeBoldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXlargeExtrabold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyXlargeExtraboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyLargeLight = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyLargeLightItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyLargeMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyLargeMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyLargeSemiboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyLargeBoldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyLargeExtrabold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyLargeExtraboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyMediumLight = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyMediumLightItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyMediumMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyMediumMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyMediumSemiboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyMediumBoldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyMediumExtrabold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyMediumExtraboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodySmallLight = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodySmallLightItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodySmallMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodySmallMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodySmallSemiboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodySmallBoldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodySmallExtrabold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodySmallExtraboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyXsmallLight = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 1.5,
  },
};

export const bodyXsmallLightItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXsmallMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyXsmallMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 500,
    lineHeight: 1.5,
  },
};

export const bodyXsmallSemiboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyXsmallBoldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXsmallExtrabold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const bodyXsmallExtraboldItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 800,
    lineHeight: 1.5,
  },
};

export const styles = {
  headingXlargeBold,
  bodyMediumRegular,
  bodyLargeRegular,
  bodyLargeBold,
  bodyLargeItalic,
  bodyMediumBold,
  bodyMediumItalic,
  bodySmallRegular,
  bodySmallBold,
  bodySmallItalic,
  headingLargeBold,
  headingMediumBold,
  headingSmallBold,
  headingXsmallBold,
  bodyXsmallRegular,
  bodyXsmallBold,
  bodyXsmallItalic,
  bodyXlargeRegular,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyXlargeSemibold,
  bodyLargeSemibold,
  bodyMediumSemibold,
  bodySmallSemibold,
  bodyXsmallSemibold,
  headingSmallSemibold,
  headingXsmallSemibold,
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXlargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingLargeItalic,
  headingMediumRegular,
  headingMediumSemibold,
  headingMediumItalic,
  headingSmallRegular,
  headingSmallItalic,
  headingXsmallRegular,
  headingXsmallItalic,
  bodyXlargeLight,
  bodyXlargeLightItalic,
  bodyXlargeMedium,
  bodyXlargeMediumItalic,
  bodyXlargeSemiboldItalic,
  bodyXlargeBoldItalic,
  bodyXlargeExtrabold,
  bodyXlargeExtraboldItalic,
  bodyLargeLight,
  bodyLargeLightItalic,
  bodyLargeMedium,
  bodyLargeMediumItalic,
  bodyLargeSemiboldItalic,
  bodyLargeBoldItalic,
  bodyLargeExtrabold,
  bodyLargeExtraboldItalic,
  bodyMediumLight,
  bodyMediumLightItalic,
  bodyMediumMedium,
  bodyMediumMediumItalic,
  bodyMediumSemiboldItalic,
  bodyMediumBoldItalic,
  bodyMediumExtrabold,
  bodyMediumExtraboldItalic,
  bodySmallLight,
  bodySmallLightItalic,
  bodySmallMedium,
  bodySmallMediumItalic,
  bodySmallSemiboldItalic,
  bodySmallBoldItalic,
  bodySmallExtrabold,
  bodySmallExtraboldItalic,
  bodyXsmallLight,
  bodyXsmallLightItalic,
  bodyXsmallMedium,
  bodyXsmallMediumItalic,
  bodyXsmallSemiboldItalic,
  bodyXsmallBoldItalic,
  bodyXsmallExtrabold,
  bodyXsmallExtraboldItalic,
};
