/* This file was generated by Supernova, don't change manually */
export const headingXlargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingXlargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingXlargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingXlargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '48px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '36px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingLargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingLargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '40px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingMediumRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingMediumSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingMediumBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const headingMediumItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '32px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingSmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingSmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingSmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const headingSmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '24px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingXsmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const headingXsmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const headingXsmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4,
  },
};

export const headingXsmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '20px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '18px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '12px',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const styles = {
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXlargeBold,
  headingXlargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingLargeBold,
  headingLargeItalic,
  headingMediumRegular,
  headingMediumSemibold,
  headingMediumBold,
  headingMediumItalic,
  headingSmallRegular,
  headingSmallSemibold,
  headingSmallBold,
  headingSmallItalic,
  headingXsmallRegular,
  headingXsmallSemibold,
  headingXsmallBold,
  headingXsmallItalic,
  bodyXlargeRegular,
  bodyXlargeSemibold,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyLargeRegular,
  bodyLargeSemibold,
  bodyLargeBold,
  bodyLargeItalic,
  bodyMediumRegular,
  bodyMediumSemibold,
  bodyMediumBold,
  bodyMediumItalic,
  bodySmallRegular,
  bodySmallSemibold,
  bodySmallBold,
  bodySmallItalic,
  bodyXsmallRegular,
  bodyXsmallSemibold,
  bodyXsmallBold,
  bodyXsmallItalic,
};
