name: 'has tags'
description: 'Has Tags'

outputs:
  has-tag:
    description: 'Whether there is a tag on the commit'
    value: ${{ steps.check-tag-exists.outputs.has-tag }}

runs:
  using: 'composite'

  steps:
    # ⚠️ This check works only if the tag is pushed alongside the commit
    # Please, use `git push && git push --tags` or `git push --follow-tags` (works only for annotated tags)
    - name: Check Tag On Commit
      id: check-tag-exists
      shell: bash
      run: |
        if [ -n "$(git tag --points-at HEAD)" ]; then
          echo "has-tag=true" >> $GITHUB_OUTPUT
        else
          echo "has-tag=false" >> $GITHUB_OUTPUT
        fi
