name: 'has tags'
description: 'Has Tags'
runs:
  using: 'composite'

  outputs:
    has-tag: ${{ steps.check-tag-exists.outputs.has-tag }}

  steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        # Even though this is set, shallow clones do not always retrieve all tags correctly
        fetch-tags: true
        # So we need to fetch full history, including all tags
        fetch-depth: 0

    # ⚠️ This check works only if the tag is pushed alongside the commit
    # Please, use `git push && git push --tags` or `git push --follow-tags` (works only for annotated tags)
    - name: Check Tag On Commit
      id: check-tag-exists
      run: |
        if [ -n "$(git tag --points-at HEAD)" ]; then
          echo "has-tag=true" >> $GITHUB_OUTPUT
        else
          echo "has-tag=false" >> $GITHUB_OUTPUT
        fi
