twig:
  default_path: '%kernel.project_dir%/templates'
  paths:
    '%kernel.project_dir%/../spirit-web-twig-bundle/src/Resources/components': 'components'

when@test:
  twig:
    strict_variables: true
