/* This file was generated by Supernova, don't change manually */
export const breakpointDesktop = '1280px';
export const breakpointMobile = 0;
export const breakpointTablet = '768px';

export const buttonLargeRadiusDesktop = '9999px';
export const buttonLargeRadiusMobile = '9999px';
export const buttonLargeRadiusTablet = '9999px';

export const buttonMediumRadiusDesktop = '9999px';
export const buttonMediumRadiusMobile = '9999px';
export const buttonMediumRadiusTablet = '9999px';

export const buttonSmallRadiusDesktop = '9999px';
export const buttonSmallRadiusMobile = '9999px';
export const buttonSmallRadiusTablet = '9999px';

export const formFieldLargeRadiusDesktop = '8px';
export const formFieldLargeRadiusMobile = '8px';
export const formFieldLargeRadiusTablet = '8px';

export const formFieldMediumRadiusDesktop = '8px';
export const formFieldMediumRadiusMobile = '8px';
export const formFieldMediumRadiusTablet = '8px';

export const formFieldSmallRadiusDesktop = '8px';
export const formFieldSmallRadiusMobile = '8px';
export const formFieldSmallRadiusTablet = '8px';

export const buttons = {
  large: {
    radius: {
      desktop: buttonLargeRadiusDesktop,
      mobile: buttonLargeRadiusMobile,
      tablet: buttonLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: buttonMediumRadiusDesktop,
      mobile: buttonMediumRadiusMobile,
      tablet: buttonMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: buttonSmallRadiusDesktop,
      mobile: buttonSmallRadiusMobile,
      tablet: buttonSmallRadiusTablet,
    },
  },
};

export const formFields = {
  large: {
    radius: {
      desktop: formFieldLargeRadiusDesktop,
      mobile: formFieldLargeRadiusMobile,
      tablet: formFieldLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: formFieldMediumRadiusDesktop,
      mobile: formFieldMediumRadiusMobile,
      tablet: formFieldMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: formFieldSmallRadiusDesktop,
      mobile: formFieldSmallRadiusMobile,
      tablet: formFieldSmallRadiusTablet,
    },
  },
};
