services:
  e2e:
    image: mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-jammy
    working_dir: /work/
    volumes:
      - ${PWD}:/work/
    ipc: host
    network_mode: host
    entrypoint: sh -c "corepack install && corepack enable && node --experimental-modules node_modules/.bin/playwright test${E2E_FLAG}"
