services:
  php:
    build:
      context: .
      dockerfile: 'Dockerfile'
      target: app_php_dev
    # To keep the image up and running
    command: tail -F anything
    volumes:
      - ./../:/srv/www/spirit-web-twig-bundle/:delegated
      - ./../../icons/src/svg/:/srv/www/spirit-web-twig-bundle/static/:delegated
