/* This file was generated by Supernova, don't change manually */
export const containerPaddingMobile = '16px';
export const containerPaddingTablet = '32px';
export const containerPaddingDesktop = '32px';

export const containerMaxWidth = '1280px';

export const breakpointMobile = 0;
export const breakpointTablet = '768px';
export const breakpointDesktop = '1280px';

export const gridSpacingMobile = '16px';
export const gridSpacingDesktop = '32px';
export const gridSpacingTablet = '32px';

export const gridColumns = '12';

export const containers = {
  padding: {
    mobile: containerPaddingMobile,
    tablet: containerPaddingTablet,
    desktop: containerPaddingDesktop,
  },
  maxWidth: containerMaxWidth,
};

export const breakpoints = {
  mobile: breakpointMobile,
  tablet: breakpointTablet,
  desktop: breakpointDesktop,
};

export const grids = {
  spacing: {
    mobile: gridSpacingMobile,
    desktop: gridSpacingDesktop,
    tablet: gridSpacingTablet,
  },
  columns: gridColumns,
};
