/* This file was generated by Supernova, don't change manually */
export const space0 = 0;
export const space100 = '1px';
export const space200 = '2px';
export const space300 = '4px';
export const space400 = '6px';
export const space500 = '8px';
export const space600 = '12px';
export const space700 = '16px';
export const space800 = '20px';
export const space900 = '24px';
export const space1000 = '32px';
export const space1100 = '40px';
export const space1200 = '48px';
export const space1300 = '56px';
export const space1400 = '64px';
export const space1500 = '72px';
export const space1600 = '80px';
export const space1700 = '96px';

export const spaces = {
  0: space0,
  100: space100,
  200: space200,
  300: space300,
  400: space400,
  500: space500,
  600: space600,
  700: space700,
  800: space800,
  900: space900,
  1000: space1000,
  1100: space1100,
  1200: space1200,
  1300: space1300,
  1400: space1400,
  1500: space1500,
  1600: space1600,
  1700: space1700,
};
