/* This file was generated by Supernova, don't change manually */
export const accent01BackgroundBasic = 'var(--spirit-color-accent-01-background-basic)';
export const accent01BackgroundSubtle = 'var(--spirit-color-accent-01-background-subtle)';
export const accent01BorderBasic = 'var(--spirit-color-accent-01-border-basic)';
export const accent01BorderSubtle = 'var(--spirit-color-accent-01-border-subtle)';
export const accent01ContentBasic = 'var(--spirit-color-accent-01-content-basic)';
export const accent01ContentSubtle = 'var(--spirit-color-accent-01-content-subtle)';
export const accent01StateActive = 'var(--spirit-color-accent-01-state-active)';
export const accent01StateDefault = 'var(--spirit-color-accent-01-state-default)';
export const accent01StateHover = 'var(--spirit-color-accent-01-state-hover)';

export const accent02BackgroundBasic = 'var(--spirit-color-accent-02-background-basic)';
export const accent02BackgroundSubtle = 'var(--spirit-color-accent-02-background-subtle)';
export const accent02BorderBasic = 'var(--spirit-color-accent-02-border-basic)';
export const accent02BorderSubtle = 'var(--spirit-color-accent-02-border-subtle)';
export const accent02ContentBasic = 'var(--spirit-color-accent-02-content-basic)';
export const accent02ContentSubtle = 'var(--spirit-color-accent-02-content-subtle)';
export const accent02StateActive = 'var(--spirit-color-accent-02-state-active)';
export const accent02StateDefault = 'var(--spirit-color-accent-02-state-default)';
export const accent02StateHover = 'var(--spirit-color-accent-02-state-hover)';

export const backgroundBackdrop = 'var(--spirit-color-background-backdrop)';

export const backgroundInteractiveStateActive = 'var(--spirit-color-background-interactive-state-active)';
export const backgroundInteractiveStateDefault = 'var(--spirit-color-background-interactive-state-default)';
export const backgroundInteractiveStateHover = 'var(--spirit-color-background-interactive-state-hover)';

export const backgroundPrimary = 'var(--spirit-color-background-primary)';
export const backgroundSecondary = 'var(--spirit-color-background-secondary)';
export const backgroundTertiary = 'var(--spirit-color-background-tertiary)';

export const borderBasic = 'var(--spirit-color-border-basic)';
export const borderFocus = 'var(--spirit-color-border-focus)';

export const borderInteractiveStateActive = 'var(--spirit-color-border-interactive-state-active)';
export const borderInteractiveStateDefault = 'var(--spirit-color-border-interactive-state-default)';
export const borderInteractiveStateHover = 'var(--spirit-color-border-interactive-state-hover)';
export const borderInteractiveStateSelected = 'var(--spirit-color-border-interactive-state-selected)';

export const componentButtonPlainBorder = 'var(--spirit-color-component-button-plain-border)';
export const componentButtonPlainContent = 'var(--spirit-color-component-button-plain-content)';
export const componentButtonPlainStateActive = 'var(--spirit-color-component-button-plain-state-active)';
export const componentButtonPlainStateDefault = 'var(--spirit-color-component-button-plain-state-default)';
export const componentButtonPlainStateHover = 'var(--spirit-color-component-button-plain-state-hover)';

export const componentButtonPrimaryBorder = 'var(--spirit-color-component-button-primary-border)';
export const componentButtonPrimaryContent = 'var(--spirit-color-component-button-primary-content)';
export const componentButtonPrimaryContentSelected = 'var(--spirit-color-component-button-primary-content-selected)';
export const componentButtonPrimaryStateActive = 'var(--spirit-color-component-button-primary-state-active)';
export const componentButtonPrimaryStateDefault = 'var(--spirit-color-component-button-primary-state-default)';
export const componentButtonPrimaryStateHover = 'var(--spirit-color-component-button-primary-state-hover)';
export const componentButtonPrimaryStateSelected = 'var(--spirit-color-component-button-primary-state-selected)';

export const componentButtonSecondaryBorder = 'var(--spirit-color-component-button-secondary-border)';
export const componentButtonSecondaryContent = 'var(--spirit-color-component-button-secondary-content)';
export const componentButtonSecondaryContentSelected = 'var(--spirit-color-component-button-secondary-content-selected)';
export const componentButtonSecondaryStateActive = 'var(--spirit-color-component-button-secondary-state-active)';
export const componentButtonSecondaryStateDefault = 'var(--spirit-color-component-button-secondary-state-default)';
export const componentButtonSecondaryStateHover = 'var(--spirit-color-component-button-secondary-state-hover)';
export const componentButtonSecondaryStateSelected = 'var(--spirit-color-component-button-secondary-state-selected)';

export const componentButtonTertiaryBorder = 'var(--spirit-color-component-button-tertiary-border)';
export const componentButtonTertiaryContent = 'var(--spirit-color-component-button-tertiary-content)';
export const componentButtonTertiaryContentSelected = 'var(--spirit-color-component-button-tertiary-content-selected)';
export const componentButtonTertiaryStateActive = 'var(--spirit-color-component-button-tertiary-state-active)';
export const componentButtonTertiaryStateDefault = 'var(--spirit-color-component-button-tertiary-state-default)';
export const componentButtonTertiaryStateHover = 'var(--spirit-color-component-button-tertiary-state-hover)';
export const componentButtonTertiaryStateSelected = 'var(--spirit-color-component-button-tertiary-state-selected)';

export const componentHeaderBackground = 'var(--spirit-color-component-header-background)';
export const componentHeaderBorder = 'var(--spirit-color-component-header-border)';
export const componentHeaderItemBackgroundStateActive = 'var(--spirit-color-component-header-item-background-state-active)';
export const componentHeaderItemBackgroundStateDefault = 'var(--spirit-color-component-header-item-background-state-default)';
export const componentHeaderItemBackgroundStateHover = 'var(--spirit-color-component-header-item-background-state-hover)';
export const componentHeaderItemBackgroundStateSelected = 'var(--spirit-color-component-header-item-background-state-selected)';
export const componentHeaderItemStateActive = 'var(--spirit-color-component-header-item-state-active)';
export const componentHeaderItemStateDefault = 'var(--spirit-color-component-header-item-state-default)';
export const componentHeaderItemStateHover = 'var(--spirit-color-component-header-item-state-hover)';
export const componentHeaderItemStateSelected = 'var(--spirit-color-component-header-item-state-selected)';
export const componentHeaderStripeStateSelected = 'var(--spirit-color-component-header-stripe-state-selected)';
export const componentHeaderStripeStateUnselected = 'var(--spirit-color-component-header-stripe-state-unselected)';

export const componentPaginationSelectedBorder = 'var(--spirit-color-component-pagination-selected-border)';
export const componentPaginationSelectedContent = 'var(--spirit-color-component-pagination-selected-content)';
export const componentPaginationSelectedStateActive = 'var(--spirit-color-component-pagination-selected-state-active)';
export const componentPaginationSelectedStateDefault = 'var(--spirit-color-component-pagination-selected-state-default)';
export const componentPaginationSelectedStateHover = 'var(--spirit-color-component-pagination-selected-state-hover)';
export const componentPaginationUnselectedBorder = 'var(--spirit-color-component-pagination-unselected-border)';
export const componentPaginationUnselectedContent = 'var(--spirit-color-component-pagination-unselected-content)';
export const componentPaginationUnselectedStateActive = 'var(--spirit-color-component-pagination-unselected-state-active)';
export const componentPaginationUnselectedStateDefault = 'var(--spirit-color-component-pagination-unselected-state-default)';
export const componentPaginationUnselectedStateHover = 'var(--spirit-color-component-pagination-unselected-state-hover)';

export const componentToggleSelectedBorder = 'var(--spirit-color-component-toggle-selected-border)';
export const componentToggleSelectedContent = 'var(--spirit-color-component-toggle-selected-content)';
export const componentToggleSelectedStateActive = 'var(--spirit-color-component-toggle-selected-state-active)';
export const componentToggleSelectedStateDefault = 'var(--spirit-color-component-toggle-selected-state-default)';
export const componentToggleSelectedStateHover = 'var(--spirit-color-component-toggle-selected-state-hover)';
export const componentToggleUnselectedBorder = 'var(--spirit-color-component-toggle-unselected-border)';
export const componentToggleUnselectedContent = 'var(--spirit-color-component-toggle-unselected-content)';
export const componentToggleUnselectedStateActive = 'var(--spirit-color-component-toggle-unselected-state-active)';
export const componentToggleUnselectedStateDefault = 'var(--spirit-color-component-toggle-unselected-state-default)';
export const componentToggleUnselectedStateHover = 'var(--spirit-color-component-toggle-unselected-state-hover)';

export const disabledBackground = 'var(--spirit-color-disabled-background)';
export const disabledBorder = 'var(--spirit-color-disabled-border)';
export const disabledContent = 'var(--spirit-color-disabled-content)';
export const disabledForeground = 'var(--spirit-color-disabled-foreground)';

export const emotionDangerBackgroundBasic = 'var(--spirit-color-emotion-danger-background-basic)';
export const emotionDangerBackgroundSubtle = 'var(--spirit-color-emotion-danger-background-subtle)';
export const emotionDangerBorderBasic = 'var(--spirit-color-emotion-danger-border-basic)';
export const emotionDangerBorderSubtle = 'var(--spirit-color-emotion-danger-border-subtle)';
export const emotionDangerContentBasic = 'var(--spirit-color-emotion-danger-content-basic)';
export const emotionDangerContentSubtle = 'var(--spirit-color-emotion-danger-content-subtle)';
export const emotionDangerStateActive = 'var(--spirit-color-emotion-danger-state-active)';
export const emotionDangerStateDefault = 'var(--spirit-color-emotion-danger-state-default)';
export const emotionDangerStateHover = 'var(--spirit-color-emotion-danger-state-hover)';

export const emotionInformativeBackgroundBasic = 'var(--spirit-color-emotion-informative-background-basic)';
export const emotionInformativeBackgroundSubtle = 'var(--spirit-color-emotion-informative-background-subtle)';
export const emotionInformativeBorderBasic = 'var(--spirit-color-emotion-informative-border-basic)';
export const emotionInformativeBorderSubtle = 'var(--spirit-color-emotion-informative-border-subtle)';
export const emotionInformativeContentBasic = 'var(--spirit-color-emotion-informative-content-basic)';
export const emotionInformativeContentSubtle = 'var(--spirit-color-emotion-informative-content-subtle)';
export const emotionInformativeStateActive = 'var(--spirit-color-emotion-informative-state-active)';
export const emotionInformativeStateDefault = 'var(--spirit-color-emotion-informative-state-default)';
export const emotionInformativeStateHover = 'var(--spirit-color-emotion-informative-state-hover)';

export const emotionSuccessBackgroundBasic = 'var(--spirit-color-emotion-success-background-basic)';
export const emotionSuccessBackgroundSubtle = 'var(--spirit-color-emotion-success-background-subtle)';
export const emotionSuccessBorderBasic = 'var(--spirit-color-emotion-success-border-basic)';
export const emotionSuccessBorderSubtle = 'var(--spirit-color-emotion-success-border-subtle)';
export const emotionSuccessContentBasic = 'var(--spirit-color-emotion-success-content-basic)';
export const emotionSuccessContentSubtle = 'var(--spirit-color-emotion-success-content-subtle)';
export const emotionSuccessStateActive = 'var(--spirit-color-emotion-success-state-active)';
export const emotionSuccessStateDefault = 'var(--spirit-color-emotion-success-state-default)';
export const emotionSuccessStateHover = 'var(--spirit-color-emotion-success-state-hover)';

export const emotionWarningBackgroundBasic = 'var(--spirit-color-emotion-warning-background-basic)';
export const emotionWarningBackgroundSubtle = 'var(--spirit-color-emotion-warning-background-subtle)';
export const emotionWarningBorderBasic = 'var(--spirit-color-emotion-warning-border-basic)';
export const emotionWarningBorderSubtle = 'var(--spirit-color-emotion-warning-border-subtle)';
export const emotionWarningContentBasic = 'var(--spirit-color-emotion-warning-content-basic)';
export const emotionWarningContentSubtle = 'var(--spirit-color-emotion-warning-content-subtle)';
export const emotionWarningStateActive = 'var(--spirit-color-emotion-warning-state-active)';
export const emotionWarningStateDefault = 'var(--spirit-color-emotion-warning-state-default)';
export const emotionWarningStateHover = 'var(--spirit-color-emotion-warning-state-hover)';

export const focusFocusRingColor01 = 'var(--spirit-color-focus-focus-ring-color-01)';

export const formFieldDanger = 'var(--spirit-color-form-field-danger)';

export const formFieldFilledBackgroundStateActive = 'var(--spirit-color-form-field-filled-background-state-active)';
export const formFieldFilledBackgroundStateDefault = 'var(--spirit-color-form-field-filled-background-state-default)';
export const formFieldFilledBackgroundStateHover = 'var(--spirit-color-form-field-filled-background-state-hover)';
export const formFieldFilledBorderStateActive = 'var(--spirit-color-form-field-filled-border-state-active)';
export const formFieldFilledBorderStateDefault = 'var(--spirit-color-form-field-filled-border-state-default)';
export const formFieldFilledBorderStateHover = 'var(--spirit-color-form-field-filled-border-state-hover)';
export const formFieldFilledBorderStateSelected = 'var(--spirit-color-form-field-filled-border-state-selected)';
export const formFieldFilledContent = 'var(--spirit-color-form-field-filled-content)';
export const formFieldFilledPlaceholder = 'var(--spirit-color-form-field-filled-placeholder)';

export const formFieldHelperText = 'var(--spirit-color-form-field-helper-text)';
export const formFieldLabel = 'var(--spirit-color-form-field-label)';
export const formFieldSuccess = 'var(--spirit-color-form-field-success)';
export const formFieldWarning = 'var(--spirit-color-form-field-warning)';

export const gradientBasicOverlayColor01 = 'var(--spirit-color-gradient-basic-overlay-color-01)';
export const gradientBasicOverlayColor02 = 'var(--spirit-color-gradient-basic-overlay-color-02)';

export const gradientPrimaryColor01 = 'var(--spirit-color-gradient-primary-color-01)';
export const gradientPrimaryColor02 = 'var(--spirit-color-gradient-primary-color-02)';

export const gradientSecondaryColor01 = 'var(--spirit-color-gradient-secondary-color-01)';
export const gradientSecondaryColor02 = 'var(--spirit-color-gradient-secondary-color-02)';

export const gradientSkeletonColor01 = 'var(--spirit-color-gradient-skeleton-color-01)';
export const gradientSkeletonColor02 = 'var(--spirit-color-gradient-skeleton-color-02)';
export const gradientSkeletonColor03 = 'var(--spirit-color-gradient-skeleton-color-03)';

export const linkPrimaryStateActive = 'var(--spirit-color-link-primary-state-active)';
export const linkPrimaryStateDefault = 'var(--spirit-color-link-primary-state-default)';
export const linkPrimaryStateHover = 'var(--spirit-color-link-primary-state-hover)';

export const linkSecondaryStateActive = 'var(--spirit-color-link-secondary-state-active)';
export const linkSecondaryStateDefault = 'var(--spirit-color-link-secondary-state-default)';
export const linkSecondaryStateHover = 'var(--spirit-color-link-secondary-state-hover)';

export const linkStateVisited = 'var(--spirit-color-link-state-visited)';

export const linkTertiaryStateActive = 'var(--spirit-color-link-tertiary-state-active)';
export const linkTertiaryStateDefault = 'var(--spirit-color-link-tertiary-state-default)';
export const linkTertiaryStateHover = 'var(--spirit-color-link-tertiary-state-hover)';

export const neutralBackgroundBasic = 'var(--spirit-color-neutral-background-basic)';
export const neutralBackgroundSubtle = 'var(--spirit-color-neutral-background-subtle)';
export const neutralBorderBasic = 'var(--spirit-color-neutral-border-basic)';
export const neutralBorderSubtle = 'var(--spirit-color-neutral-border-subtle)';
export const neutralContentBasic = 'var(--spirit-color-neutral-content-basic)';
export const neutralContentSubtle = 'var(--spirit-color-neutral-content-subtle)';
export const neutralStateActive = 'var(--spirit-color-neutral-state-active)';
export const neutralStateDefault = 'var(--spirit-color-neutral-state-default)';
export const neutralStateHover = 'var(--spirit-color-neutral-state-hover)';

export const selectedContentBasic = 'var(--spirit-color-selected-content-basic)';
export const selectedContentSubtle = 'var(--spirit-color-selected-content-subtle)';
export const selectedStateActive = 'var(--spirit-color-selected-state-active)';
export const selectedStateDefault = 'var(--spirit-color-selected-state-default)';
export const selectedStateHover = 'var(--spirit-color-selected-state-hover)';

export const shadowShadow100Color01 = 'var(--spirit-color-shadow-shadow-100-color-01)';

export const shadowShadow200Color01 = 'var(--spirit-color-shadow-shadow-200-color-01)';

export const shadowShadow300Color01 = 'var(--spirit-color-shadow-shadow-300-color-01)';

export const shadowShadow400Color01 = 'var(--spirit-color-shadow-shadow-400-color-01)';

export const textPrimary = 'var(--spirit-color-text-primary)';
export const textSecondary = 'var(--spirit-color-text-secondary)';
export const textTertiary = 'var(--spirit-color-text-tertiary)';

export const accentColors = {
  '01': {
    backgroundBasic: accent01BackgroundBasic,
    backgroundSubtle: accent01BackgroundSubtle,
    borderBasic: accent01BorderBasic,
    borderSubtle: accent01BorderSubtle,
    contentBasic: accent01ContentBasic,
    contentSubtle: accent01ContentSubtle,
    stateActive: accent01StateActive,
    stateDefault: accent01StateDefault,
    stateHover: accent01StateHover,
  },
  '02': {
    backgroundBasic: accent02BackgroundBasic,
    backgroundSubtle: accent02BackgroundSubtle,
    borderBasic: accent02BorderBasic,
    borderSubtle: accent02BorderSubtle,
    contentBasic: accent02ContentBasic,
    contentSubtle: accent02ContentSubtle,
    stateActive: accent02StateActive,
    stateDefault: accent02StateDefault,
    stateHover: accent02StateHover,
  },
};

export const backgroundColors = {
  backdrop: backgroundBackdrop,
  interactive: {
    stateActive: backgroundInteractiveStateActive,
    stateDefault: backgroundInteractiveStateDefault,
    stateHover: backgroundInteractiveStateHover,
  },
  primary: backgroundPrimary,
  secondary: backgroundSecondary,
  tertiary: backgroundTertiary,
};

export const borderColors = {
  basic: borderBasic,
  focus: borderFocus,
  interactive: {
    stateActive: borderInteractiveStateActive,
    stateDefault: borderInteractiveStateDefault,
    stateHover: borderInteractiveStateHover,
    stateSelected: borderInteractiveStateSelected,
  },
};

export const componentColors = {
  button: {
    plain: {
      border: componentButtonPlainBorder,
      content: componentButtonPlainContent,
      stateActive: componentButtonPlainStateActive,
      stateDefault: componentButtonPlainStateDefault,
      stateHover: componentButtonPlainStateHover,
    },
    primary: {
      border: componentButtonPrimaryBorder,
      content: componentButtonPrimaryContent,
      contentSelected: componentButtonPrimaryContentSelected,
      stateActive: componentButtonPrimaryStateActive,
      stateDefault: componentButtonPrimaryStateDefault,
      stateHover: componentButtonPrimaryStateHover,
      stateSelected: componentButtonPrimaryStateSelected,
    },
    secondary: {
      border: componentButtonSecondaryBorder,
      content: componentButtonSecondaryContent,
      contentSelected: componentButtonSecondaryContentSelected,
      stateActive: componentButtonSecondaryStateActive,
      stateDefault: componentButtonSecondaryStateDefault,
      stateHover: componentButtonSecondaryStateHover,
      stateSelected: componentButtonSecondaryStateSelected,
    },
    tertiary: {
      border: componentButtonTertiaryBorder,
      content: componentButtonTertiaryContent,
      contentSelected: componentButtonTertiaryContentSelected,
      stateActive: componentButtonTertiaryStateActive,
      stateDefault: componentButtonTertiaryStateDefault,
      stateHover: componentButtonTertiaryStateHover,
      stateSelected: componentButtonTertiaryStateSelected,
    },
  },
  header: {
    background: componentHeaderBackground,
    border: componentHeaderBorder,
    itemBackgroundStateActive: componentHeaderItemBackgroundStateActive,
    itemBackgroundStateDefault: componentHeaderItemBackgroundStateDefault,
    itemBackgroundStateHover: componentHeaderItemBackgroundStateHover,
    itemBackgroundStateSelected: componentHeaderItemBackgroundStateSelected,
    itemStateActive: componentHeaderItemStateActive,
    itemStateDefault: componentHeaderItemStateDefault,
    itemStateHover: componentHeaderItemStateHover,
    itemStateSelected: componentHeaderItemStateSelected,
    stripeStateSelected: componentHeaderStripeStateSelected,
    stripeStateUnselected: componentHeaderStripeStateUnselected,
  },
  pagination: {
    selectedBorder: componentPaginationSelectedBorder,
    selectedContent: componentPaginationSelectedContent,
    selectedStateActive: componentPaginationSelectedStateActive,
    selectedStateDefault: componentPaginationSelectedStateDefault,
    selectedStateHover: componentPaginationSelectedStateHover,
    unselectedBorder: componentPaginationUnselectedBorder,
    unselectedContent: componentPaginationUnselectedContent,
    unselectedStateActive: componentPaginationUnselectedStateActive,
    unselectedStateDefault: componentPaginationUnselectedStateDefault,
    unselectedStateHover: componentPaginationUnselectedStateHover,
  },
  toggle: {
    selectedBorder: componentToggleSelectedBorder,
    selectedContent: componentToggleSelectedContent,
    selectedStateActive: componentToggleSelectedStateActive,
    selectedStateDefault: componentToggleSelectedStateDefault,
    selectedStateHover: componentToggleSelectedStateHover,
    unselectedBorder: componentToggleUnselectedBorder,
    unselectedContent: componentToggleUnselectedContent,
    unselectedStateActive: componentToggleUnselectedStateActive,
    unselectedStateDefault: componentToggleUnselectedStateDefault,
    unselectedStateHover: componentToggleUnselectedStateHover,
  },
};

export const disabledColors = {
  background: disabledBackground,
  border: disabledBorder,
  content: disabledContent,
  foreground: disabledForeground,
};

export const emotionColors = {
  danger: {
    backgroundBasic: emotionDangerBackgroundBasic,
    backgroundSubtle: emotionDangerBackgroundSubtle,
    borderBasic: emotionDangerBorderBasic,
    borderSubtle: emotionDangerBorderSubtle,
    contentBasic: emotionDangerContentBasic,
    contentSubtle: emotionDangerContentSubtle,
    stateActive: emotionDangerStateActive,
    stateDefault: emotionDangerStateDefault,
    stateHover: emotionDangerStateHover,
  },
  informative: {
    backgroundBasic: emotionInformativeBackgroundBasic,
    backgroundSubtle: emotionInformativeBackgroundSubtle,
    borderBasic: emotionInformativeBorderBasic,
    borderSubtle: emotionInformativeBorderSubtle,
    contentBasic: emotionInformativeContentBasic,
    contentSubtle: emotionInformativeContentSubtle,
    stateActive: emotionInformativeStateActive,
    stateDefault: emotionInformativeStateDefault,
    stateHover: emotionInformativeStateHover,
  },
  success: {
    backgroundBasic: emotionSuccessBackgroundBasic,
    backgroundSubtle: emotionSuccessBackgroundSubtle,
    borderBasic: emotionSuccessBorderBasic,
    borderSubtle: emotionSuccessBorderSubtle,
    contentBasic: emotionSuccessContentBasic,
    contentSubtle: emotionSuccessContentSubtle,
    stateActive: emotionSuccessStateActive,
    stateDefault: emotionSuccessStateDefault,
    stateHover: emotionSuccessStateHover,
  },
  warning: {
    backgroundBasic: emotionWarningBackgroundBasic,
    backgroundSubtle: emotionWarningBackgroundSubtle,
    borderBasic: emotionWarningBorderBasic,
    borderSubtle: emotionWarningBorderSubtle,
    contentBasic: emotionWarningContentBasic,
    contentSubtle: emotionWarningContentSubtle,
    stateActive: emotionWarningStateActive,
    stateDefault: emotionWarningStateDefault,
    stateHover: emotionWarningStateHover,
  },
};

export const focusColors = {
  focusRing: {
    color01: focusFocusRingColor01,
  },
};

export const formFieldColors = {
  danger: formFieldDanger,
  filled: {
    backgroundStateActive: formFieldFilledBackgroundStateActive,
    backgroundStateDefault: formFieldFilledBackgroundStateDefault,
    backgroundStateHover: formFieldFilledBackgroundStateHover,
    borderStateActive: formFieldFilledBorderStateActive,
    borderStateDefault: formFieldFilledBorderStateDefault,
    borderStateHover: formFieldFilledBorderStateHover,
    borderStateSelected: formFieldFilledBorderStateSelected,
    content: formFieldFilledContent,
    placeholder: formFieldFilledPlaceholder,
  },
  helperText: formFieldHelperText,
  label: formFieldLabel,
  success: formFieldSuccess,
  warning: formFieldWarning,
};

export const gradientColors = {
  basicOverlay: {
    color01: gradientBasicOverlayColor01,
    color02: gradientBasicOverlayColor02,
  },
  primary: {
    color01: gradientPrimaryColor01,
    color02: gradientPrimaryColor02,
  },
  secondary: {
    color01: gradientSecondaryColor01,
    color02: gradientSecondaryColor02,
  },
  skeleton: {
    color01: gradientSkeletonColor01,
    color02: gradientSkeletonColor02,
    color03: gradientSkeletonColor03,
  },
};

export const linkColors = {
  primary: {
    stateActive: linkPrimaryStateActive,
    stateDefault: linkPrimaryStateDefault,
    stateHover: linkPrimaryStateHover,
  },
  secondary: {
    stateActive: linkSecondaryStateActive,
    stateDefault: linkSecondaryStateDefault,
    stateHover: linkSecondaryStateHover,
  },
  stateVisited: linkStateVisited,
  tertiary: {
    stateActive: linkTertiaryStateActive,
    stateDefault: linkTertiaryStateDefault,
    stateHover: linkTertiaryStateHover,
  },
};

export const neutralColors = {
  backgroundBasic: neutralBackgroundBasic,
  backgroundSubtle: neutralBackgroundSubtle,
  borderBasic: neutralBorderBasic,
  borderSubtle: neutralBorderSubtle,
  contentBasic: neutralContentBasic,
  contentSubtle: neutralContentSubtle,
  stateActive: neutralStateActive,
  stateDefault: neutralStateDefault,
  stateHover: neutralStateHover,
};

export const selectedColors = {
  contentBasic: selectedContentBasic,
  contentSubtle: selectedContentSubtle,
  stateActive: selectedStateActive,
  stateDefault: selectedStateDefault,
  stateHover: selectedStateHover,
};

export const shadowColors = {
  shadow100: {
    color01: shadowShadow100Color01,
  },
  shadow200: {
    color01: shadowShadow200Color01,
  },
  shadow300: {
    color01: shadowShadow300Color01,
  },
  shadow400: {
    color01: shadowShadow400Color01,
  },
};

export const textColors = {
  primary: textPrimary,
  secondary: textSecondary,
  tertiary: textTertiary,
};

export const colors = {
  accent: accentColors,
  background: backgroundColors,
  border: borderColors,
  component: componentColors,
  disabled: disabledColors,
  emotion: emotionColors,
  focus: focusColors,
  formField: formFieldColors,
  gradient: gradientColors,
  link: linkColors,
  neutral: neutralColors,
  selected: selectedColors,
  shadow: shadowColors,
  text: textColors,
};
