# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: spirit-web-twig-demo

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: eu-west-1
  # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
  stage: dev
  runtime: provided.al2
  environment:
    # Symfony environment variables
    APP_ENV: prod
    BREF_PING_DISABLE: 1

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  # This function runs the Symfony website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: '*'

package:
  patterns:
    # Excluded files and folders for deployment
    - '!assets/**'
    - '!node_modules/**'
    - '!public/build/**'
    - '!tests/**'
    - '!var/**'
    # If you want to include files and folders that are part of excluded folders,
    # add them at the end
    - 'var/cache/prod/**'
    - 'public/build/entrypoints.json'
    - 'public/build/manifest.json'

constructs:
  website:
    type: server-side-website
    assets:
      # '/bundles/*': public/bundles
      '/build/*': public/build
      # '/favicon.ico': public/favicon.ico
      # '/robots.txt': public/robots.txt
      # add here any file or directory that needs to be served from S3
