import { TokenGroup, Token, TokenType, DimensionToken } from '@supernovaio/sdk-exporters';
import { CSSHelper, NamingHelper, StringCase } from '@supernovaio/export-helpers';
import { exportConfiguration } from '../index';

type TokenHandler = (token: Token, mappedTokens: Map<string, Token>, tokenGroups: TokenGroup[]) => string | null;

const tokenVariableName = (token: Token, tokenGroups: Array<TokenGroup>, withoutParent: boolean = false): string => {
  let parent;
  if (withoutParent) {
    parent = null;
  } else {
    parent = tokenGroups.find((group) => group.id === token.parentGroupId)!;
  }

  return NamingHelper.codeSafeVariableNameForToken(token, StringCase.paramCase, parent, '');
};

const addDisclaimer = (content: string): string => {
  if (exportConfiguration.generateDisclaimer) {
    return `/* This file was generated by Supernova, don't change by hand */\n${content}`;
  }

  return content;
};

export const generateContent = (
  tokens: Array<Token>,
  mappedTokens: Map<string, Token>,
  tokenGroups: Array<TokenGroup>,
) => {
  return [
    {
      fileName: '_spacing.scss',
      content: createSpacingContent(tokens, mappedTokens, tokenGroups),
    },
  ];
};

const filterTokensByType = (tokens: Token[], type: TokenType): Token[] => {
  return tokens.filter((t) => t.tokenType === type);
};

const tokensToCSS = (
  tokens: Token[],
  handler: TokenHandler,
  mappedTokens: Map<string, Token>,
  tokenGroups: Array<TokenGroup>,
): string => {
  return tokens
    .map((token) => handler(token, mappedTokens, tokenGroups))
    .filter(Boolean)
    .join('\n');
};

export const measuresTokenToCSS = (
  token: Token,
  mappedTokens: Map<string, Token>,
  tokenGroups: Array<TokenGroup>,
): string | null => {
  if (token.tokenType !== TokenType.dimension) {
    return null;
  }

  const dimensionToken = token as DimensionToken;
  // @ts-ignore-next-line
  if (!token.origin.name?.includes('Spacing system')) {
    return null;
  }

  const name = tokenVariableName(dimensionToken, tokenGroups, true);
  const value = dimensionToken.value.measure;
  const unit = CSSHelper.unitToCSS(dimensionToken.value.unit);

  return `$${name}: ${value}${unit} !default;`;
};

export const createSpacingContent = (
  tokens: Token[],
  mappedTokens: Map<string, Token>,
  tokenGroups: Array<TokenGroup>,
) => {
  const filteredSpacingTokens = filterTokensByType(tokens, TokenType.dimension);
  const spacingTokensToCSS = tokensToCSS(filteredSpacingTokens, measuresTokenToCSS, mappedTokens, tokenGroups);
  const spacingObject = generateSpacesObject(tokens, mappedTokens, tokenGroups);

  return addDisclaimer(`${spacingTokensToCSS}\n\n${spacingObject}`);
};

export const generateSpacesObject = (
  tokens: Array<Token>,
  mappedTokens: Map<string, Token>,
  tokenGroups: Array<TokenGroup>,
): string => {
  let spacesObject = '$spaces: (\n';

  tokens.forEach((token) => {
    if (token.tokenType === TokenType.dimension && token.origin?.name?.includes('Spacing system')) {
      const dimensionToken = token as DimensionToken;
      const name = tokenVariableName(dimensionToken, tokenGroups, true);
      const numericPart = name.match(/\d+/)?.[0];
      if (numericPart) {
        spacesObject += `    ${numericPart}: $${name},\n`;
      }
    }
  });

  spacesObject += ') !default;';

  return spacesObject;
};
