/* This file was generated by Supernova, don't change manually */
export const backgroundBackdrop = '#1a1b1b80';

export const backgroundInteractiveStateActive = '#ffffff1a';
export const backgroundInteractiveStateDefault = '#fff0';
export const backgroundInteractiveStateHover = '#ffffff0d';

export const backgroundPrimary = '#6039cc';
export const backgroundSecondary = '#3c2480';
export const backgroundTertiary = '#1e1240';

export const borderBasic = '#a07eff';
export const borderFocus = '#1e1240';

export const borderInteractiveStateActive = '#bba3ff';
export const borderInteractiveStateDefault = '#a07eff';
export const borderInteractiveStateHover = '#ae91ff';
export const borderInteractiveStateSelected = '#ffbe00';

export const componentButtonPlainBorder = '#fff0';
export const componentButtonPlainContent = '#fff';
export const componentButtonPlainStateActive = '#ffffff26';
export const componentButtonPlainStateDefault = '#fff0';
export const componentButtonPlainStateHover = '#ffffff1a';

export const componentButtonPrimaryBorder = '#1e1240';
export const componentButtonPrimaryContent = '#3c2480';
export const componentButtonPrimaryStateActive = '#e4daff';
export const componentButtonPrimaryStateDefault = '#fff';
export const componentButtonPrimaryStateHover = '#f1edff';

export const componentButtonSecondaryBorder = '#f8f6ff';
export const componentButtonSecondaryContent = '#fff';
export const componentButtonSecondaryStateActive = '#1a1b1b26';
export const componentButtonSecondaryStateDefault = '#1a1b1b00';
export const componentButtonSecondaryStateHover = '#1a1b1b1a';

export const componentButtonTertiaryBorder = '#1a1b1b00';
export const componentButtonTertiaryContent = '#fff';
export const componentButtonTertiaryStateActive = '#1a1b1b4d';
export const componentButtonTertiaryStateDefault = '#1a1b1b33';
export const componentButtonTertiaryStateHover = '#1a1b1b40';

export const componentHeaderBackground = '#6039cc';
export const componentHeaderItemBackgroundStateActive = '#1a1b1b26';
export const componentHeaderItemBackgroundStateDefault = '#fff0';
export const componentHeaderItemBackgroundStateHover = '#1a1b1b1a';
export const componentHeaderItemBackgroundStateSelected = '#fff0';
export const componentHeaderItemStateActive = '#e5e5e5';
export const componentHeaderItemStateDefault = '#fff';
export const componentHeaderItemStateHover = '#f2f2f2';
export const componentHeaderItemStateSelected = '#ffbe00';
export const componentHeaderStripeStateSelected = '#fff';
export const componentHeaderStripeStateUnselected = '#ffffff40';

export const componentToggleSelectedBorder = '#a07eff';
export const componentToggleSelectedContent = '#fff';
export const componentToggleSelectedStateActive = '#3e9b4f';
export const componentToggleSelectedStateDefault = '#327c3f';
export const componentToggleSelectedStateHover = '#388b47';
export const componentToggleUnselectedBorder = '#a07eff';
export const componentToggleUnselectedContent = '#4e2ea6';
export const componentToggleUnselectedStateActive = '#e4daff';
export const componentToggleUnselectedStateDefault = '#fff';
export const componentToggleUnselectedStateHover = '#f1edff';

export const disabledBackground = '#ffffff1a';
export const disabledBorder = '#fff3';
export const disabledContent = '#ffffff80';
export const disabledForeground = '#fff3';

export const emotionDangerBackgroundBasic = '#e40000';
export const emotionDangerBackgroundSubtle = '#fce5e5';
export const emotionDangerBorderBasic = '#e93333';
export const emotionDangerBorderSubtle = '#ef6666';
export const emotionDangerContentBasic = '#720000';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerStateActive = '#ec4d4d';
export const emotionDangerStateDefault = '#e40000';
export const emotionDangerStateHover = '#e93333';

export const emotionInformativeBackgroundBasic = '#0066d8';
export const emotionInformativeBackgroundSubtle = '#e5f0fb';
export const emotionInformativeBorderBasic = '#3385e0';
export const emotionInformativeBorderSubtle = '#66a3e8';
export const emotionInformativeContentBasic = '#00336c';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeStateActive = '#4d94e4';
export const emotionInformativeStateDefault = '#0066d8';
export const emotionInformativeStateHover = '#3385e0';

export const emotionSuccessBackgroundBasic = '#3e9b4f';
export const emotionSuccessBackgroundSubtle = '#ecf5ed';
export const emotionSuccessBorderBasic = '#65af72';
export const emotionSuccessBorderSubtle = '#8bc395';
export const emotionSuccessContentBasic = '#1f4e28';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessStateActive = '#78b984';
export const emotionSuccessStateDefault = '#3e9b4f';
export const emotionSuccessStateHover = '#65af72';

export const emotionWarningBackgroundBasic = '#f27d00';
export const emotionWarningBackgroundSubtle = '#fef2e5';
export const emotionWarningBorderBasic = '#f59733';
export const emotionWarningBorderSubtle = '#f7b166';
export const emotionWarningContentBasic = '#793f00';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningStateActive = '#f6a44d';
export const emotionWarningStateDefault = '#f27d00';
export const emotionWarningStateHover = '#f59733';

export const focusFocusRingColor01 = '#d2c2ffb2';

export const formFieldDanger = '#ec4d4d';

export const formFieldFilledBackgroundStateActive = '#fff';
export const formFieldFilledBackgroundStateDefault = '#f9f9f9';
export const formFieldFilledBackgroundStateHover = '#f1edff';
export const formFieldFilledBorderStateActive = '#936cff';
export const formFieldFilledBorderStateDefault = '#ae91ff';
export const formFieldFilledBorderStateHover = '#a07eff';
export const formFieldFilledBorderStateSelected = '#ffbe00';
export const formFieldFilledContent = '#202020';
export const formFieldFilledPlaceholder = '#666';

export const formFieldHelperText = '#c9b5ff';
export const formFieldLabel = '#fff';
export const formFieldSuccess = '#78b984';
export const formFieldWarning = '#f6a44d';

export const gradientBasicOverlayColor01 = '#606060';
export const gradientBasicOverlayColor02 = '#60606000';

export const linkPrimaryStateActive = '#e5e5e5';
export const linkPrimaryStateDefault = '#fff';
export const linkPrimaryStateHover = '#f2f2f2';

export const linkSecondaryStateActive = '#e5e5e5';
export const linkSecondaryStateDefault = '#d6c8ff';
export const linkSecondaryStateHover = '#f2f2f2';

export const linkStateVisited = '#ffbe00';

export const linkTertiaryStateActive = '#e5e5e5';
export const linkTertiaryStateDefault = '#bba3ff';
export const linkTertiaryStateHover = '#f2f2f2';

export const neutralBackgroundBasic = '#202020';
export const neutralBackgroundSubtle = '#f2f2f2';
export const neutralBorderBasic = '#202020';
export const neutralBorderSubtle = '#bfbfbf';
export const neutralContentBasic = '#202020';
export const neutralContentSubtle = '#fff';
export const neutralStateActive = '#535353';
export const neutralStateDefault = '#202020';
export const neutralStateHover = '#404040';

export const selectedContentBasic = '#fff';
export const selectedContentSubtle = '#3c2480';
export const selectedStateActive = '#ffd24d';
export const selectedStateDefault = '#ffbe00';
export const selectedStateHover = '#ffcb33';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#f9f9f9';
export const textSecondary = '#d9d9d9';
export const textTertiary = '#b2b2b2';
