index:
  path: /
  controller: App\Controller\DefaultController::index

component_view:
  path: /components/{component}
  controller: App\Controller\ComponentsController::show

icons_index:
  path: /icons
  controller: App\Controller\IconsController::index

helpers_index:
  path: /helpers
  controller: App\Controller\HelpersController::index

helper_view:
  path: /helpers/{helper}
  controller: App\Controller\HelpersController::show

validations_index:
  path: /validations
  controller: App\Controller\ValidationsController::index
