name: Format Check

on:
  push:
    branches-ignore:
      - main

jobs:
  check-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check format
        run: yarn format:check
