name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags origin main

      - run: make install

      - name: Authenticate npm
        run: ./bin/ci/npm-auth.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version
        run: make version

      - name: Release
        run: make release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
