name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn install --frozen-lockfile
          yarn storybook:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .storybook/build # The folder that the storybook:build script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # The folder that we serve our Storybook files from
